### DISCUSSION TITLE
blog/2022/deploy/

### DISCUSSION THREAD

**Discussion by giscus** [go-gost/gost#380] [General]
# blog/2022/deploy/

https://gost.run/blog/2022/deploy/

**Comment by mzbgf** [comment]
分享一下我遇到的问题和解决办法


在开启Cloudflare CDN后，我发现我无法通过上述方式正确连接到我的服务器，原因是Cloudflare CDN根据域名分流到对应的服务器，而gost默认不发送Host，以下是我的解决办法:

在客户端运行以下命令将服务器映射到本地
```gost -C client.yaml```


client.yaml:
```
services:
  - name: service-0
    addr: :10000
    handler:
      type: tcp
      chain: chain-0
      metadata:
        sniffing: true
    listener:
      type: tcp
    forwarder:
      nodes:
        - name: target-0
          http:
            host: SITE_DOMAIN
chains:
  - name: chain-0
    hops:
      - name: hop-0
        nodes:
          - name: node-0
            addr: SITE_IP:443
            connector:
              type: forward
            dialer:
              type: tls
              tls:
                serverName: SITE_DOMAIN
```
注: SITE_DOMAIN相当于原文中的(*.)gost.run
SITE_IP是SITE_DOMAIN对应的优选ip

然后运行以下命令连接到gost隧道:
```gost -L :8080 -F relay+ws://:10000```
