### DISCUSSION TITLE
concepts/bypass/

### DISCUSSION THREAD

**Discussion by giscus** [go-gost/gost#466] [General]
# concepts/bypass/

https://gost.run/concepts/bypass/

**Comment by zzzz0317** [comment]
我在Bypass列表中添加了

```
127.0.0.1/8
10.0.0.0/8
172.16.0.0/12
192.168.0.0/16
100.64.0.0/10
```

经过测试，直接访问IP地址确实被拦截了，但如果访问一个解析到内网IP地址的域名，还是可以放问的，应该怎么搞呢？

附上配置文件

```yaml
services:
- name: service-0
  addr: ":1080"
  bypass: bypass-0
  handler:
    type: socks5
  listener:
    type: tcp
bypasses:
- name: bypass-0
  reload: 10s
  whitelist: false
  file:
    path: /srv/gost/conf/bypass.list
```

**Reply by ginuerzh** [reply]
把域名添加到bypass就可以了。

**Comment by wuchuwei** [comment]
所有插件都支持grpc吗？

**Reply by ginuerzh** [reply]
支持。

**Comment by yhgroup** [comment]
分流器组“当任何一个分流器规则未匹配成功则代表未通过”没法达到想要的功能：要访问多个域名网站，每个网站都是bypasses下的一个白名单节点，默认通过一个分流器组包含所有域名想走同一个跳跃点（下面转发链节点上配置的是一个二级代理），假如某个网站当前跳跃点访问存在问题可以修改到改到另一个跳跃点（另一个二级代理）。分流器组配置的多个分流器要是能只要一个匹配就行是否能支持。

**Reply by yhgroup** [reply]
按分流器组配置文件上的两个一个黑名单一个白名单，实际传入的除非白名单范围中包含了黑名单的不然永远不会存在黑白名单都匹配吧。

**Comment by yhgroup** [comment]
services:
- name: service-0
  addr: ":3128"
  handler:
    type: http
    chain: chain-0
  listener:
    type: tcp
chains:
- name: chain-0
  bypass: bypass-0
  hops:
  - name: hop-0
    bypass: bypass-0
    nodes:
    - name: node-0
      addr: 192.168.0.122:8888
      connector:
        type: http
      dialer:
        type: tcp
  - name: hop-1
    bypass: bypass-1
    nodes:
    - name: node-0
      addr: 192.168.0.123:8888
      connector:
        type: http
      dialer:
        type: tcp
bypasses:
- name: bypass-0
  whitelist: true
  matchers:
  - .credit.gd.gov.cn
- name: bypass-1
  whitelist: true
  matchers:
  - .szcredit.org.cn

上面访问www.credit.gd.gov.cn的走hop-0访问到二级代理，访问www.szcredit.org.cn的不走hop-1。不知是什么问题！

**Reply by ginuerzh** [reply]
.szcredit.org.cn也要加入到bypass-0中，否则在hop-0级别就已经过滤掉了。

**Reply by yhgroup** [reply]
是按优先级处理的，前面都得符合才会走到后面?hop是并行与关系的？不是或关系！这样达不到我这边想要的场景了。windows下Proxifier的代理规则，优先级未命中可以下一个规则命中就行，防火墙上的规则优先级也这样。gost第一个没命中就过滤掉不往后匹配这种我都想到的什么场景下需要

**Reply by yhgroup** [reply]
如果有5个二级代理节点绑定在不同hop下要分别指定不同域名，那后面的域名要在前面的每个bypass都要设置，这样搞得有点复杂

**Reply by ginuerzh** [reply]
不同的hop代表不同层级，是一种串联关系，类似于流水线，任何一级通不过，就会终止。
你可能需要的是一个hop中有多个节点的情况：
```yaml
chains:
- name: chain-0
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      addr: 192.168.0.122:8888
      bypass: bypass-0
      connector:
        type: http
      dialer:
        type: tcp
    - name: node-1
      addr: 192.168.0.123:8888
      bypass: bypass-1
      connector:
        type: http
      dialer:
        type: tcp
```
