### DISCUSSION TITLE
concepts/observer/

### DISCUSSION THREAD

**Discussion by giscus** [go-gost/gost#557] [General]
# concepts/observer/

https://gost.run/concepts/observer/

**Comment by longbill** [comment]
我在本地用nodejs写了一个http服务器接收observer的消息。yaml配置文件里面也正确配置了：

`
services:
- name: service1
  addr: ":1763"
  handler:
    type: socks5
    chain: chain1
    observer: observer1
    metadata:
      observePeriod: 5s
  listener:
    type: tcp

observers:
- name: observer1
  plugin:
    addr: 127.0.0.1:8000
`

但是无论我有没有监听本地的8000端口，gost日志里面都报这个错误：

{"kind":"observer","level":"error","msg":"rpc error: code = Unavailable desc = connection error: desc = \"error reading server preface: http2: frame too large\"","observer":"observer1","time":"2024-08-12T14:39:39.846+08:00"}

**Reply by longbill** [reply]
gost版本为  gost v3.0.0-nightly.20240806 (go1.22.5 darwin/arm64)

**Reply by longbill** [reply]
更换为http就好了。
```
observers:
- name: observer1
  plugin:
    type: http
    addr: http://127.0.0.1:8000/observer
    timeout: 2s
```
