### DISCUSSION TITLE
How to enable socks5 udp?

### DISCUSSION THREAD

**Discussion by Naruse-developer** [go-gost/gost#576] [Q&A]
gost.yaml

```yaml
services:
- name: service-sosks5
  addr: :8888
  handler:
    type: socks5
    auth:
      username: 123456
      password: 123456
  listener:
    type: rtcp
log:
  level: error
  format: json
  output: C:\gost\test\log.log
  rotation:
    maxSize: 1000
    maxAge: 30
    maxBackups: 1
    localTime: true
    compress: false
```

log

```json
{"cmd":"udp","handler":"socks5","kind":"handler","level":"error","listener":"rtcp","local":"192.168.2.200:8888","msg":"socks5: UDP relay is disabled","remote":"192.168.2.1:41106","service":"service-sosks5","time":"2024-09-12T18:19:54.169+08:00","user":"123456"}
```

**Comment by Naruse-developer** [comment]
gost.yml
```yaml
services:
- name: service-sosks5
  addr: :8888
  handler:
    type: socks5
    auth:
      username: 123456
      password: 123456
    metadata:
      udp: true
      udpBufferSize: 4096
      notls: true
  listener:
    type: tcp
log:
  level: info
  format: json
  output: C:\gost\test\log.log
  rotation:
    maxSize: 1000
    maxAge: 30
    maxBackups: 1
    localTime: true
    compress: false
```

UDP TEST : UDP Blocked
