### DISCUSSION TITLE
concepts/load-balancing/

### DISCUSSION THREAD

**Discussion by giscus** [go-gost/gost#585] [General]
# concepts/load-balancing/

https://gost.run/concepts/load-balancing/

**Comment by molezz** [comment]
多个node负载均衡如何配置权重， 比如node1： node2是30:70 ？

```
services:
- name: service-0
  addr: ":8080"
  handler:
    type: auto
    chain: chain-0
  listener:
    type: tcp
chains:
- name: chain-0
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      addr: 192.168.1.1:8080
      connector:
        type: http
      dialer:
        type: tcp
    - name: node-1
      addr: 192.168.2.1:8080
      connector:
        type: http
      dialer:
        type: tcp
```
