### ISSUE TITLE
当配置多个DNS时，请求逻辑是什么样的

### ISSUE THREAD

**Issue by liaohongxing** [go-gost/gost#117]
```
services:
- name: service-0
  addr: :10053
  handler:
    type: dns
    # chain: chain-0
  listener:
    type: dns
    metadata:
      mode: udp
  forwarder:
    nodes:
    - name: target-0
      addr: 1.1.1.1
    - name: target-1
      addr: tls://1.1.1.1:853
```

比如上面配置 ，可以看到 target-0  , target-1  。 他们之间的请求逻辑是什么样的。并发请求还是 前面的优先
