### ISSUE TITLE
透明代理支持ipv6

### ISSUE THREAD

**Issue by islercn** [go-gost/gost#126]
透明代理对ipv6的支持一直没有实现，目前3.0rc0依然还是不支持（socks代理等支持），不知日后是否有支持计划？

**Comment by fernvenue** [comment]
Can be reproduced, and I just found out that we can create an IPv6 port forwarding service point to an IPv4 transparent proxy service, so that we can do IPv6 transparent proxy on gost for now.

Hope gost can support IPv6 transparent proxy service natively :)

**Comment by islercn** [comment]
请问这个问题还有解决的计划吗？ @ginuerzh

**Comment by ginuerzh** [comment]
优先级较低，短期内无计划，同时欢迎PR。

**Comment by ginuerzh** [comment]
最新提交已经支持ipv6。

**Comment by fernvenue** [comment]
Hi @ginuerzh, thanks for your update. But I got an issue here, this is an IPv4 based TPROXY service:

```
~$ curl -I https://youtube.com --resolve youtube.com:443:198.18.169.1
HTTP/2 301
```

And this one is an IPv6 based TPROXY service:

```
~$ curl -I https://youtube.com --resolve youtube.com:443:2001:db8:169::1
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to youtube.com:443
```

The IPv4 TPROXY test log:

```
gost[5863]: {"dst":"198.18.169.1:443/tcp","handler":"red","host":"youtube.com:443","kind":"handler","level":"info","listener":"red","local":"198.18.169.1:443","msg":"198.18.186.42:54320 <-> youtube.com:443","remote":"198.18.186.42:54320","service":"red4-https","time":"2024-07-11T23:20:30.529+06:00"}
```

The IPv6 TPROXY test log, this is the related one I can found:

```
gost[5863]: {"handler":"red","kind":"handler","level":"info","listener":"tcp","local":"[2001:db8:169::1]:443","msg":"[2001:db8:186::42]:36008 <> [2001:db8:169::1]:443","remote":"[2001:db8:186::42]:36008","service":"red6-https","time":"2024-07-11T23:26:28.211+06:00"}
```

And the version:

```
~# gost -V       
gost v3.0.0-nightly.20240711 (go1.22.5 linux/amd64)
```

Part of my configuration:

```
- name: red4-http
  addr: "198.18.169.1:80"
  sockopts:
    mark: 100
  handler:
    type: red
    chain: chain-01
    metadata:
      sniffing: true
  listener:
    type: red
- name: red4-https
  addr: "198.18.169.1:443"
  sockopts:
    mark: 100
  handler:
    type: red
    chain: chain-01
    metadata:
      sniffing: true
  listener:
    type: red
- name: red6-http
  addr: "[2001:db8:169::1]:80"
  sockopts:
    mark: 100
  handler:
    type: red
    chain: chain-01
    metadata:
      sniffing: true
  listener:
    type: tcp
- name: red6-https
  addr: "[2001:db8:169::1]:443"
  sockopts:
    mark: 100
  handler:
    type: red
    chain: chain-01
    metadata:
      sniffing: true
  listener:
    type: tcp
```

May or may not related to https://github.com/go-gost/gost/issues/379? I'm not sure, feel free to tell me if anything I can help with :)
