### ISSUE TITLE
DNS处理器不能利用chain吗？

### ISSUE THREAD

**Issue by aa51513** [go-gost/gost#13]
【这样配置，不通】
```
- name: service-1
  addr: ":10053"
  handler:
    type: dns
    chain: chain-0
  listener:
    type: dns
    metadata:
      mode: tls
      dns: 1.1.1.1:853
```

【这样配置，还是不通】
```
- name: service-1
  addr: ":10053"
  handler:
    type: dns
  listener:
    type: dns
    chain: chain-0
    metadata:
      mode: tls
      dns: 1.1.1.1:853
```
【目前只能这么用着】
```
- name: service-1
  addr: :10053
  handler:
    type: udp
    chain: chain-0
  listener:
    type: udp
  forwarder:
    targets:
    - 1.1.1.1:53
```

**Comment by ginuerzh** [comment]
```
services:
- name: service-0
  addr: :10053
  handler:
    type: dns
    chain: chain-0
    metadata:
      dns:
      - tls://1.1.1.1:853
  listener:
    type: dns
    metadata:
       mode: udp
```

`mode`是控制本地开启的DNS代理服务运行模式。
`dns`参数要设在handler上，是一个列表。
