### ISSUE TITLE
Could we update a service using API do not close the "old" service?

### ISSUE THREAD

**Issue by xzycn** [go-gost/gost#142]
In my case, I want to change the limiter of a service dynamically ,but now the implementation has some problems for me:

1.  [it will close the old service](https://github.com/go-gost/x/blob/master/api/config_service.go#L106), so the service will be unavailable in downtime,it is unacceptable for a network-sensitive application 
2. I must post whole specs(including addr、handler, etc.) of the service,I just want to change the limit at the moment :(

For the 1st problem, can we use SO_REUSEADDR or SO_REUSEPORT,so we can create the new service and then close the old one.Otherwise, only recreate a new service when a **addr** field or other important fields changed.

For the 2nd problem, gost can provide a API for patching like kubectl apply.

Thanks.

**Comment by xzycn** [comment]
@ginuerzh indeed.
I want to update limiter a service to use, for example:
```yaml
services:
  - name: service-1
    addr: :2516
    limiter: limiter-2m
```
to
```yaml
services:
  - name: service-1
    addr: :2516
    limiter: limiter-5m
```
