### ISSUE TITLE
远程端口转发并开启sniffing，能不能实现多个客户端转发至同一端口？

### ISSUE THREAD

**Issue by kssion** [go-gost/gost#157]
我有两个主机A和B，想通过 192.168.3.2:80 根据不同的域名来访问各自的服务，现在的问题是A绑定了80端口，B就不能绑定80了，有什么解决方法吗？

主机A
```
services:
- name: http
  addr: :80
  handler:
    type: rtcp
    metadata:
      sniffing: true
  listener:
    type: rtcp
    chain: chain-0
  forwarder:
    nodes:
    - name: local-0
      addr: 127.0.0.1:8000
      host: x00.example.com
    - name: local-1
      addr: 127.0.0.1:8001
      host: x11.example.com
chains:
- name: chain-0
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      addr: 192.168.3.2:8443
      connector:
        type: socks5
      dialer:
        type: tcp
```

主机B
```
services:
- name: http
  addr: :80
  handler:
    type: rtcp
    metadata:
      sniffing: true
  listener:
    type: rtcp
    chain: chain-0
  forwarder:
    nodes:
    - name: local-0
      addr: 127.0.0.1:8080
      host: x22.example.com
chains:
- name: chain-0
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      addr: 192.168.3.2:8443
      connector:
        type: socks5
      dialer:
        type: tcp
```

**Comment by xzycn** [comment]
A，B是不同的主机，为什么"A绑定了80端口，B就不能绑定80了"？

**Comment by ginuerzh** [comment]
A和B绑定的不是本地端口，而是192.168.3.2上的80端口。
解决方法是只能分开绑定不同的端口，再通过前置代理来路由。

**Comment by kssion** [comment]
如果分开绑定不同的端口，假设我新增一个主机C，那么C绑定了82端口，这时主机192.168.3.2是不是也需要修改相应的配置，来支持82端口的目标主机？

我目前在用远程端口转发+nginx来实现的，但是每新增一个远程端口就需要在nginx增加一个反向代理。前几天看到v3中的反向代理支持配置域名，但同时也遇到了端口绑定的限制。

其实我想实现的是类似“ngrok”的功能，做内网穿透，客户端随时都可以连接而不需要代理端的任何改动，这样就完美了，是否考虑扩展一下？

**Comment by ginuerzh** [comment]
https://gost.run/tutorials/reverse-proxy-advanced/
这个功能或许能够满足。

**Comment by kssion** [comment]
> https://gost.run/tutorials/reverse-proxy-advanced/
> 这个功能或许能够满足。

感谢！这正是我想要的。测试发现有一个问题
同一个隧道一个客户端连接时正常
当两个客户端同时连接时，访问任一主机会出现随机访问的现象，两个主机的服务会依次被访问

访问主机 A sub1.example.com
> 第1次：A: sub1
> 第2次：B: fallback
> 第3次：A: sub1
> 第4次：B: fallback
> ...

访问主机 B sub3.example.com
> 结果：
> 第1次：B: sub3
> 第2次：A: fallback
> 第3次：B: sub3
> 第4次：A: fallback
> ...


# 下边是客户端的配置文件：

# Host A
```
services:
- name: service-0
  addr: :0
  handler:
    type: rtcp
    metadata:
      sniffing: true
  listener:
    type: rtcp
    chain: chain-0
  forwarder:
    nodes:
    - name: sub1
      addr: :8001
      host: sub1.example.com
    - name: sub2
      addr: :8002
      host: sub2.example.com
    - name: fallback
      addr: :8000
chains:
- name: chain-0
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      addr: example.com:9000
      connector:
        type: relay
        metadata:
          tunnelID: ac74d9dd-3125-442a-a7c1-f9e49e05faca
      dialer:
        type: tcp
```

# Host B
```
services:
- name: service-0
  addr: :0
  handler:
    type: rtcp
    metadata:
      sniffing: true
  listener:
    type: rtcp
    chain: chain-0
  forwarder:
    nodes:
    - name: sub3
      addr: :8003
      host: sub3.example.com
    - name: fallback
      addr: :8000
chains:
- name: chain-0
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      addr: example.com:9000
      connector:
        type: relay
        metadata:
          tunnelID: ac74d9dd-3125-442a-a7c1-f9e49e05faca
      dialer:
        type: tcp
```

![image](https://user-images.githubusercontent.com/12656299/212480908-e715abdc-9a55-42b5-b942-a21b3cea785c.jpg)
