### ISSUE TITLE
功能需求：指定数据出口IP

### ISSUE THREAD

**Issue by steamsv** [go-gost/gost#18]
例如：服务器有多个公网ip(ipv4或ipv6)，能够设定走指定ip出去，实现多ip利用

**Comment by ginuerzh** [comment]
https://latest.gost.run/tutorials/multi-homed/

**Comment by steamsv** [comment]
使用以下配置，还是默认148出口
```
services:
- name: service-0
  addr: ":10001"
  interface: 92.38.185.148
  handler:
    type: socks
    auther: auther-0
  listener:
    type: tcp
- name: service-2
  addr: ":10002"
  interface: 92.38.185.149
  handler:
    type: socks
    auther: auther-0
  listener:
    type: tcp
authers:
- name: auther-0
  auths:
  - username: vgubtr
    password: bvigrieirbiuve
```
