### ISSUE TITLE
v3的ssh是否还存在ping的参数?

### ISSUE THREAD

**Issue by xxxsen** [go-gost/gost#185]
将配置从v2迁移到v3后, 发现不知道怎么配置相关的ping参数, 查了下文档, 貌似也没有关于这块的配置, 还请作者帮忙解答下。

原先的配置:
```shell
gost -L=:1080 -F=ssh://111:111@pp_client:1080?ping=12
```

这个是重写后的v3配置
```yml
...
chains:
- name: sshforward-1080
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      addr: "pp_client:1080"
      connector:
        type: sshd
        auth:
          username: 123
          password: 123
      dialer:
        type: sshd
```
