### ISSUE TITLE
使用最新docker镜像时，grpc连接报错

### ISSUE THREAD

**Issue by windrosecn** [go-gost/gost#188]
错误信息：ClientConn's authority from transport creds <domain name> and dial option <ip address> don't match

客户端 docker-compose.yml
```
version: '3'
services:
  gost:
    image: gogost/gost
    container_name: gost-grpc
    network_mode: host
    restart: unless-stopped
    command:
      - "-L=redir://:${REDIR_PORT}"
      - "-F=relay+grpc://${GOST_USER}:${PASS}@${DOMAIN}:${REMOTE_PORT}?hosts=${DOMAIN}:${IP_ADDR}"
```

服务器端 docker-compose.yml
```
version: '3'

services:
  gost-grpc:
    image: gogost/gost
    container_name: gost-grpc
    restart: unless-stopped
    networks:
      - traefik-net
    command: "-L relay+grpc://${GOST_USER}:${PASS}@:${LISTEN_PORT}?grpcInsecure=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gost-grpc.tls=true"
      - "traefik.http.routers.gost-grpc.tls.certresolver=letsencrypt"
      - "traefik.http.routers.gost-grpc.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.gost-grpc.entrypoints=https"
      - "traefik.http.services.gost-grpc.loadbalancer.server.port=${LISTEN_PORT}"
      - "traefik.http.services.gost-grpc.loadbalancer.server.scheme=h2c"
      - "traefik.docker.network=traefik-net"

networks:
  traefik-net:
    external: true
```

同样配置用3.0.0-rc6及之前的镜像可正常工作。换成relay+websocket则新镜像也可正常工作。
