### ISSUE TITLE
socks5认证无效

### ISSUE THREAD

**Issue by steamsv** [go-gost/gost#19]
yaml配置
```
services:
- name: socks5
  addr: ":21080"
  # bypass: bypass01
  handler:
    type: socks5
    # chain: chain-ss
    metadata:
      auths:
       - gost:gost
      readTimeout: 5s
      notls: true
      bind: true
      udp: true
      # udpBufferSize: 4096 # range [512, 66560]
  listener:
    type: tcp
    metadata:
      keepAlive: 15s
```

yaml命令行转json后的配置
```
{
  "services": [
    {
      "name": "socks5",
      "addr": ":21080",
      "handler": {
        "type": "socks",
        "metadata": {
          "auths": [
            "gost:gost"
          ],
          "bind": true,
          "notls": true,
          "readTimeout": "5s",
          "udp": true
        }
      },
      "listener": {
        "type": "tcp",
        "metadata": {
          "keepAlive": "15s"
        }
      }
    }
  ]
}
```

无法连接，等我回家给log
