### ISSUE TITLE
is it possible to do conditional routing/forwarding?

### ISSUE THREAD

**Issue by vahobrsti** [go-gost/gost#211]
Here is the scenario: 

request 1 from ip1 
request 2 from ip2 

if request is being originated from ip1 on port 443, use otls and forward to server 1 on port 1443
if request is being originated from ip2, use wss and forward it to server2 on port 2443

**Comment by ginuerzh** [comment]
You can start two separate services, listening on different address:
```
gost -L tcp://ip1:443 -F forward+otls://server1:1443
```
```
gost -L tcp://:ip2:443 -F forward+wss://server2:2443
```
Or, use configuration file:
```
services:
  - name: service-0
    addr: ip1:443
    handler:
      type: tcp
      chain: chain-0
    listener:
      type: tcp
  - name: service-1
    addr: ip2:443
    handler:
      type: tcp
      chain: chain-1
    listener:
      type: tcp
chains:
  - name: chain-0
    hops:
      - name: hop-0
        nodes:
          - name: node-0
            addr: server1:1443
            connector:
              type: forward
            dialer:
              type: otls
  - name: chain-1
    hops:
      - name: hop-0
        nodes:
          - name: node-0
            addr: server2:2443
            connector:
              type: forward
            dialer:
              type: wss
```
