### ISSUE TITLE
SOCKS5 通过转发链chain,只支持tcp,不支持 UDP转发

### ISSUE THREAD

**Issue by agaolong** [go-gost/gost#224]
配置如下:
```yaml
services:
- name: service-0
  addr: ":8000"
  handler:
    type: auto
    chain: chain-0
    metadata:
      udp: true
      notls: true
      bind: true
  listener:
    type: tcp
chains:
- name: chain-0
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      addr: 8.8.8.8:8888
      connector:
        type: ss
        auth:
          username: AEAD_CHACHA20_POLY1305
          password: "12345678"
      dialer:
        type: tcp
```
怎么样配置才能让SOCKS5支持udp呢?ss是支持udp的

**Comment by chengziqing** [comment]
[35:02]  TCP测试开始.
[35:02]  正在测试TCP数据传递...
[35:02]  连接到SS节点...
[35:02]  已连接到SS节点.
[35:02]  测试TCP数据传递...通过!
[35:02]  延迟: 1 ms
[35:02]  测试完成!
[35:02]  //////////////////////////////////////////////
[35:02]  UDP测试开始.
[35:02]  正在测试UDP转发...
[35:02]  正在从代理服务器请求UDP转发...
[35:02]  不能连接到代理.
[35:02]  测试UDP转发...未通过!
[35:02]  测试完成!
[35:02]  //////////////////////////////////////////////

**Comment by woodlyer** [comment]
https://latest.gost.run/tutorials/protocols/socks/
gost的文档中说的是这种支持UDP的方法。  
通过端口映射的方式  
```
gost -L socks5://:1080?udp=true
gost -L udp://:10053/:53 -F socks5://:1080
```

用这里面的方法实测，gost 实现的socks5协议本身并不支持udp
https://unix.stackexchange.com/questions/732672/check-whether-socks5-proxy-server-support-udp

```
echo hello | socksify nc -u  server  1080
```

**Comment by chengziqing** [comment]
@woodlyer 
可能你没明白我的意思.gost socks5本身是支持udp的.但是通过转发链后,udp功能就不能用了

**Comment by openwrt2223** [comment]
> 配置如下: services:
> 
> * name: service-0
>   addr: ":8000"
>   handler:
>   type: auto
>   chain: chain-0
>   metadata:
>   udp: true
>   notls: true
>   bind: true
>   listener:
>   type: tcp
>   chains:
> * name: chain-0
>   hops:
>   
>   * name: hop-0
>     nodes:
>     
>     * name: node-0
>       addr: 8.8.8.8:8888
>       connector:
>       type: ss
>       auth:
>       username: AEAD_CHACHA20_POLY1305
>       password: "12345678"
>       dialer:
>       type: tcp
> 
> 怎么样配置才能让SOCKS5支持udp呢?ss是支持udp的

你没看文献？
ssu处理器使用Shadowsocks UDP转发协议进行数据交互，用于转发UDP数据。
详见:https://gost.run/reference/handlers/ssu/

**Comment by ginuerzh** [comment]
shadowsocks的TCP和UDP是分开的两个服务：
```yaml
services:
- name: service-0
  addr: ":8000"
  handler:
    type: auto
    chain: chain-0
    metadata:
      udp: true
      notls: true
      bind: true
  listener:
    type: tcp
chains:
- name: chain-0
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      addr: 8.8.8.8:8888
      connector:
        type: ssu
        auth:
          username: AEAD_CHACHA20_POLY1305
          password: "12345678"
      dialer:
        type: udp
        metadata:
          keepalive: true
          ttl: 30s
```
