### ISSUE TITLE
作为 sni proxy client，hosts 参数支持 catch-all 或者 . (根域名) 匹配 IP 进行连接

### ISSUE THREAD

**Issue by wen-long** [go-gost/gost#228]
https://gost.run/concepts/hosts/
如果 hosts 参数支持 hosts=.:127.0.0.1 此时相当于 gost client 将 127.0.0.1 视为 sniproxy 进行连接，且可以连接到不同端口

这种方式可能比现有的 -F=sni:// 更好

当前如果想实现同等功能，我是采用 mosdos 配置 black_hole，即不论域名如何，返回指定的 IP，同时 gost 指定 ?dns=$mosdns

可否讨论一下

附 mosdos 配置
```
log:
    level: info
plugins:

  - tag: remote_sequence
    type: sequence
    args:
      - exec: black_hole $sniproxy_ip

  - type: udp_server
    args:
      entry: remote_sequence
      listen: 127.0.0.1:5533
```

**Comment by wen-long** [comment]
相关 https://github.com/go-gost/gost/issues/79

**Comment by ginuerzh** [comment]
hosts支持catch-all没问题，但不太理解你上面所说的使用场景。

**Comment by ginuerzh** [comment]
Support for catch-all hosts mapping has been added via commit [go-gost/x@48f3151](https://github.com/go-gost/x/commit/48f3151ead1527f1d2a6a555ea7664daf8e662d3).

**Usage**: A `hostname: "."` entry acts as a catch-all that matches any unmatched hostname.

```yaml
hosts:
  mappings:
  - hostname: .
    ip: 127.0.0.1
```

**How it works**: The catch-all is the last-resort fallback after the existing three-phase matching (exact → dot-prefix → suffix walk). More specific rules still take priority:

```yaml
hosts:
  mappings:
  - hostname: .example.com
    ip: 10.0.0.1
  - hostname: .
    ip: 127.0.0.1
```
