### ISSUE TITLE
Allow configuring handler/dialer timeout

### ISSUE THREAD

**Issue by L2501** [go-gost/gost#229]
The default timeout of 10 seconds is too short for many cases

**Comment by ginuerzh** [comment]
A new `dialTimeout` option has been added to the service to set the timeout in the latest version:
```
gost -L :16666?dialTimeout=10s
```
or
```yaml
services:
- name: service-0
  addr: ":16666"
  handler:
    type: http
  listener:
    type: tcp
  metadata:
    dialTimeout: 10s
```

今天的nightly版本中可用。
