### ISSUE TITLE
指定出口IPV4后IPV6网站无法访问

### ISSUE THREAD

**Issue by GuerraMorgan** [go-gost/gost#23]
VPS单个网卡同时包含多个IPV4和一个IPV6
GOST指定出口IPV4后IPV6网站无法访问，当不指定interface时IPV6网站可以访问
IP已用本地IP代替，VPS环境上都是公网IP
GOST配置如下
```
services:
- name: service-0
  addr: "127.0.0.1:80"
  interface: 127.0.0.1
  handler:
    type: http
    auther: auther-0
  listener:
    type: tcp
- name: service-1
  addr: "127.0.0.2:80"
  interface: 127.0.0.2
  handler:
    type: http
    auther: auther-0
  listener:
    type: tcp
- name: service-2
  addr: "127.0.0.3:80"
  interface: 127.0.0.3
  handler:
    type: http
    auther: auther-0
  listener:
    type: tcp
authers:
- name: auther-0
  auths:
  - username: admin
    password: admin
```
