### ISSUE TITLE
PROXY Protocol 似乎在某些情况下不起作用

### ISSUE THREAD

**Issue by Glucy-2** [go-gost/gost#238]
配置了一个内网穿透，但是后面的服务获取不了访客真实IP
服务端和客户端用的都是amd64v3的[v3.0.0-rc8](https://github.com/go-gost/gost/releases/tag/v3.0.0-rc8)，服务端在 Debian 11 上，客户端在 Debian 12 上
配置文件和日志如下：

- 服务端：
```yml
services:
- name: ports
  addr: :12288
  handler:
    type: relay
    auth:
      username: xxxxx+user
      password: super/secret
    metadata:
      bind: true
      proxyProtocol: 2
  metadata:
    proxyProtocol: 2
  listener:
    type: tcp
```

<details><summary>日志</summary>
<pre>
Jun 26 02:31:18 （服务端） gost[1463]: {"handler":"relay","kind":"service","level":"info","listener":"tcp","msg":"listening on [::]:12288/tcp","service":"ports","time":"2023-06-26T02:31:18.411+08:00"}
Jun 26 02:31:19 （服务端） gost[1463]: {"handler":"relay","kind":"handler","level":"info","listener":"tcp","local":"172.16.0.62:12288","msg":"（客户端IP）:47532 <> 172.16.0.62:12288","remote":"（客户端IP）:47532","service":"ports","time":"2023-06-26T02:31:19.259+08:00"}
Jun 26 02:32:18 （服务端） gost[1463]: {"handler":"relay","kind":"handler","level":"info","listener":"tcp","local":"172.16.0.62:12288","msg":"（客户端IP）:50508 <> 172.16.0.62:12288","remote":"（客户端IP）:50508","service":"ports","time":"2023-06-26T02:32:18.837+08:00"}
Jun 26 02:54:10 （服务端） gost[1463]: {"bind":"[::]:25565/tcp","cmd":"bind","dst":":25565/tcp","handler":"ep-tcp","kind":"handler","level":"info","listener":"tcp","local":"172.16.0.62:25565","msg":"（访客IP）:32536 <> 172.16.0.62:25565","remote":"（访客IP）:32536","service":"ports-ep-[::]:25565","time":"2023-06-26T02:54:10.279+08:00","user":"xxxxx+user"}
Jun 26 02:54:10 （服务端） gost[1463]: {"bind":"[::]:25565/tcp","cmd":"bind","dst":":25565/tcp","duration":84311832,"handler":"ep-tcp","kind":"handler","level":"info","listener":"tcp","local":"172.16.0.62:25565","msg":"（访客IP）:32536 >< 172.16.0.62:25565","remote":"（访客IP）:32536","service":"ports-ep-[::]:25565","time":"2023-06-26T02:54:10.363+08:00","user":"xxxxx+user"}
Jun 26 02:54:10 （服务端） gost[1463]: {"bind":"[::]:25565/tcp","cmd":"bind","dst":":25565/tcp","handler":"ep-tcp","kind":"handler","level":"info","listener":"tcp","local":"172.16.0.62:25565","msg":"（访客IP）:54443 <> 172.16.0.62:25565","remote":"（访客IP）:54443","service":"ports-ep-[::]:25565","time":"2023-06-26T02:54:10.397+08:00","user":"xxxxx+user"}
Jun 26 02:54:25 （服务端） gost[1463]: {"bind":"[::]:25565/tcp","cmd":"bind","dst":":25565/tcp","duration":15165926162,"handler":"ep-tcp","kind":"handler","level":"info","listener":"tcp","local":"172.16.0.62:25565","msg":"（访客IP）:54443 >< 172.16.0.62:25565","remote":"（访客IP）:54443","service":"ports-ep-[::]:25565","time":"2023-06-26T02:54:25.563+08:00","user":"xxxxx+user"}
Jun 26 02:54:29 （服务端） gost[1463]: {"bind":"[::]:25565/tcp","cmd":"bind","dst":":25565/tcp","handler":"ep-tcp","kind":"handler","level":"info","listener":"tcp","local":"172.16.0.62:25565","msg":"（访客IP）:55147 <> 172.16.0.62:25565","remote":"（访客IP）:55147","service":"ports-ep-[::]:25565","time":"2023-06-26T02:54:29.912+08:00","user":"xxxxx+user"}
Jun 26 02:54:29 （服务端） gost[1463]: {"bind":"[::]:25565/tcp","cmd":"bind","dst":":25565/tcp","duration":76350849,"handler":"ep-tcp","kind":"handler","level":"info","listener":"tcp","local":"172.16.0.62:25565","msg":"（访客IP）:55147 >< 172.16.0.62:25565","remote":"（访客IP）:55147","service":"ports-ep-[::]:25565","time":"2023-06-26T02:54:29.988+08:00","user":"xxxxx+user"}
</pre>
</details> 

- 客户端：
```yml
services:
- name: MCJE
  addr: :25565
  handler:
    type: rtcp
  listener:
    type: rtcp
    chain: port-chain
  metadata:
    proxyProtocol: 2
  forwarder:
    nodes:
    - name: MCJE
      addr: :25565
- name: port-chain
  hops:
  - name: hop-0
    nodes:
    - name: cn-sd
      addr: cn-sd.example.com:12288
      connector:
        type: relay
        auth:
          username: xxxxx+user
          password: super/secret
      metadata:
        proxyProtocol: 2
      dialer:
        type: tcp
```

<details><summary>日志</summary>
<pre>
Jun 26 02:31:37 （客户端） gost[47620]: {"handler":"rtcp","kind":"service","level":"info","listener":"rtcp","msg":"listening on :25565/tcp","service":"MCJE","time":"2023-06-26T02:31:37.475+08:00"}
Jun 26 02:32:34 （客户端） gost[47620]: {"handler":"rtcp","kind":"listener","level":"error","listener":"rtcp","msg":"route(retry=0) timeout: no recent network activity","service":"MCJE","time":"2023-06-26T02:32:34.043+08:00"}
Jun 26 02:32:34 （客户端） gost[47620]: {"handler":"rtcp","kind":"service","level":"warning","listener":"rtcp","msg":"accept: timeout: no recent network activity, retrying in 1s","service":"MCJE","time":"2023-06-26T02:32:34.043+08:00"}
Jun 26 02:32:35 （客户端） gost[47620]: {"handler":"rtcp","kind":"listener","level":"error","listener":"rtcp","msg":"route(retry=0) timeout: no recent network activity","service":"MCJE","time":"2023-06-26T02:32:35.090+08:00"}
Jun 26 02:32:35 （客户端） gost[47620]: {"handler":"rtcp","kind":"service","level":"warning","listener":"rtcp","msg":"accept: timeout: no recent network activity, retrying in 2s","service":"MCJE","time":"2023-06-26T02:32:35.090+08:00"}
Jun 26 02:54:28 （客户端） gost[47620]: {"handler":"rtcp","kind":"handler","level":"info","listener":"rtcp","local":"[::]:25565","msg":"（访客IP）:32536 <> [::]:25565","remote":"（访客IP）:32536","service":"MCJE","time":"2023-06-26T02:54:28.588+08:00"}
Jun 26 02:54:28 （客户端） gost[47620]: {"dst":":25565/tcp","handler":"rtcp","host":"","kind":"handler","level":"info","listener":"rtcp","local":"[::]:25565","msg":"（访客IP）:32536 <-> :25565","node":"MCJE","remote":"（访客IP）:32536","service":"MCJE","time":"2023-06-26T02:54:28.589+08:00"}
Jun 26 02:54:28 （客户端） gost[47620]: {"dst":":25565/tcp","duration":80411088,"handler":"rtcp","host":"","kind":"handler","level":"info","listener":"rtcp","local":"[::]:25565","msg":"（访客IP）:32536 >-< :25565","node":"MCJE","remote":"（访客IP）:32536","service":"MCJE","time":"2023-06-26T02:54:28.669+08:00"}
Jun 26 02:54:28 （客户端） gost[47620]: {"dst":":25565/tcp","duration":81000286,"handler":"rtcp","host":"","kind":"handler","level":"info","listener":"rtcp","local":"[::]:25565","msg":"（访客IP）:32536 >< [::]:25565","node":"MCJE","remote":"（访客IP）:32536","service":"MCJE","time":"2023-06-26T02:54:28.669+08:00"}
Jun 26 02:54:28 （客户端） gost[47620]: {"handler":"rtcp","kind":"handler","level":"info","listener":"rtcp","local":"[::]:25565","msg":"（访客IP）:54443 <> [::]:25565","remote":"（访客IP）:54443","service":"MCJE","time":"2023-06-26T02:54:28.704+08:00"}
Jun 26 02:54:28 （客户端） gost[47620]: {"dst":":25565/tcp","handler":"rtcp","host":"","kind":"handler","level":"info","listener":"rtcp","local":"[::]:25565","msg":"（访客IP）:54443 <-> :25565","node":"MCJE","remote":"（访客IP）:54443","service":"MCJE","time":"2023-06-26T02:54:28.704+08:00"}
Jun 26 02:54:43 （客户端） gost[47620]: {"dst":":25565/tcp","duration":15164665521,"handler":"rtcp","host":"","kind":"handler","level":"info","listener":"rtcp","local":"[::]:25565","msg":"（访客IP）:54443 >-< :25565","node":"MCJE","remote":"（访客IP）:54443","service":"MCJE","time":"2023-06-26T02:54:43.869+08:00"}
Jun 26 02:54:43 （客户端） gost[47620]: {"dst":":25565/tcp","duration":15165214211,"handler":"rtcp","host":"","kind":"handler","level":"info","listener":"rtcp","local":"[::]:25565","msg":"（访客IP）:54443 >< [::]:25565","node":"MCJE","remote":"（访客IP）:54443","service":"MCJE","time":"2023-06-26T02:54:43.869+08:00"}
Jun 26 02:54:48 （客户端） gost[47620]: {"handler":"rtcp","kind":"handler","level":"info","listener":"rtcp","local":"[::]:25565","msg":"（访客IP）:55147 <> [::]:25565","remote":"（访客IP）:55147","service":"MCJE","time":"2023-06-26T02:54:48.219+08:00"}
Jun 26 02:54:48 （客户端） gost[47620]: {"dst":":25565/tcp","handler":"rtcp","host":"","kind":"handler","level":"info","listener":"rtcp","local":"[::]:25565","msg":"（访客IP）:55147 <-> :25565","node":"MCJE","remote":"（访客IP）:55147","service":"MCJE","time":"2023-06-26T02:54:48.220+08:00"}
Jun 26 02:54:48 （客户端） gost[47620]: {"dst":":25565/tcp","duration":63351198,"handler":"rtcp","host":"","kind":"handler","level":"info","listener":"rtcp","local":"[::]:25565","msg":"（访客IP）:55147 >-< :25565","node":"MCJE","remote":"（访客IP）:55147","service":"MCJE","time":"2023-06-26T02:54:48.283+08:00"}
Jun 26 02:54:48 （客户端） gost[47620]: {"dst":":25565/tcp","duration":64042014,"handler":"rtcp","host":"","kind":"handler","level":"info","listener":"rtcp","local":"[::]:25565","msg":"（访客IP）:55147 >< [::]:25565","node":"MCJE","remote":"（访客IP）:55147","service":"MCJE","time":"2023-06-26T02:54:48.283+08:00"}
</pre>
</details>

但是客户端25565端口上的服务看到的访客IP一直是127.0.0.1（服务是没有问题的，用其他反向代理或者内网穿透服务器开启 PROXY Protocol 是可以看到访客真实IP的）

是我的配置有误，还是程序bug，或是其他什么原因？

**Comment by ginuerzh** [comment]
最新的提交中rtcp已经支持发送PROXY Protocol。
```yaml
services:
- name: MCJE
  addr: :25565
  handler:
    type: rtcp
    metadata:
      proxyProtocol: 2
  listener:
    type: rtcp
    chain: port-chain
  forwarder:
    nodes:
    - name: MCJE
      addr: :25565
```
