### ISSUE TITLE
Redirect + HTTP-Connect: Usage with Squid

### ISSUE THREAD

**Issue by NiceRath** [go-gost/gost#261]
Greetings!

Thank you for developing this useful tool!

The [transparent proxy - redirect](https://latest.gost.run/en/tutorials/redirect/#redirect) + [http-tunnel - connect-method](https://latest.gost.run/en/tutorials/http-tunnel/#http-connect-method) will not work to connect to an existing Squid server.

Is there some option to change this behavior? Else I would call that a bug - as this behavior would be expected and can be useful in situations when you don't control the (Squid) Proxy server.

Setup: `Client =TCP=> gost@127.0.0.1 =HTTP[TCP]=> remote Squid Proxy`

It seems like gost does not handle the HTTP-Proxy connection the same way as usual integrations (*like in browsers/http-agents/...*).
It looks like it does also create a HTTP-connect 'tunnel' through the 'forwarding' server to the actual target:

```
# usual implementation
Client =HTTP[TCP]=> remote Squid Proxy =TCP=> Target
# gost implementation
Client =HTTP[TCP]=> remote Squid Proxy =HTTP[TCP]=> Target
```

Gost config used:
```yaml
#!/tmp/gost -D -C
---

services:
  - name: service-0
    addr: 127.0.0.1:3128
    handler:
      type: red
      chain: chain-0
      metadata:
        sniffing: "true"
    listener:
      type: red
      metadata:
        sniffing: "true"
    metadata:
      sniffing: "true"
chains:
  - name: chain-0
    hops:
      - name: hop-0
        nodes:
          - name: node-0
            addr: <PROXY-IP>:3128
            connector:
              type: http
            dialer:
              type: tcp
```

Squid logs:
* usual connection
  ```
  NONE/200 0 CONNECT <TARGET-DNS>:443
  TCP_TUNNEL/200 6149 CONNECT <TARGET-DNS>:443
  TCP_MISS/200 2485 GET <TARGET-DNS>:80
  ```

* connection made by gost

  * if 'CONNECT' is allowed by squid AND the target
    ```
    NONE/200 0 CONNECT <TARGET-DNS>:443
    TCP_TUNNEL/200 406 CONNECT <TARGET-DNS>:443
    ```

  * if either squid or the target does not support it
    ```
    NONE/200 0 CONNECT <TARGET-DNS>:443
    TCP_DENIED_ABORTED/200 0 CONNECT <TARGET-DNS>:443
    TCP_DENIED_ABORTED/200 0 CONNECT <TARGET-DNS>:80
    ```

Redirect to gost:

```nft
#!/usr/sbin/nft -f
...
chain output_dnat {
    type nat hook output priority -100; policy accept;
    tcp dport { 80, 443 } ip daddr != { 10.0.0.0/8, 127.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 } dnat ip to 127.0.0.1:3128
}
...
```

Squid config to allow or dis-allow CONNECT:

* allow => gost can connect to any target
    ```
    acl CONNECT method CONNECT
    acl ssl_ports port 443
    acl step1 at_step SslBump1

    http_access deny CONNECT !ssl_ports
    http_access allow CONNECT  # <=
    ssl_bump peek step1 ssl_ports
    ssl_bump splice all
    ```

* deny => gost can't connect at all
    ```
    acl CONNECT method CONNECT
    acl ssl_ports port 443
    acl step1 at_step SslBump1

    http_access deny CONNECT !ssl_ports
    http_access allow CONNECT step1  # <=
    ssl_bump peek step1 ssl_ports
    ssl_bump splice all
    ```
