### ISSUE TITLE
gost的选择器会出现标黑失败的bug

### ISSUE THREAD

**Issue by k0njac** [go-gost/gost#271]
现象：当某个 协议连接失败的时候 取不到失败次数和时间，导致会无限重试某个节点
客户端配置文件。
```
services:
  - name: service-0
    addr: 192.168.31.215:80
    handler:
      type: tcp
      chainGroup:
        chains: 
          - chain-1
          - chain-6
        selector:
            strategy: round
            maxFails: 1
            failTimeout: 600s
    listener:
      type: tcp
    forwarder:
      nodes:
        - name: target-0
          addr: 192.168.31.171:8080
chains:
  - name: chain-1
    hops:
      - name: hop-0
        nodes:
          - name: node-0
            addr: :8081
            connector:
              type: http2
              auth:
                username: test
                password: test
            dialer:
              type: http2
  - name: chain-6
    hops:
      - name: hop-0
        nodes:
          - name: node-0
            addr: 192.168.31.171:8443
            connector:
              type: http
            dialer:
              type: ssh
```

假如我开了chain1和chain6，当chain1连接失败的时候，会触发标记，我跟踪了一下代码，x/handler/forward/local/handler.go的确是调用了Mark函数进行标记，并且次数是+1了，Time也成功赋值为当前时间。
但是x/selector/filter.go中，
```
any(v).(selector.Markable)中 取的mark.Count()和mark.Time()都取不到正确的值，只取到了初始的值。
```
这样子就永远符合if条件 导致执行了l=append(l,v)
导致节点会一直被重试
我试了一下 不是所有的协议都会这样子，只有部分协议会出现这个问题。我不是很会golang的any特性，研究了2天，实在想不到特别优雅的修复方案和导致取不到正确值的问题是什么
