### ISSUE TITLE
负载均衡失败总是选取第一个  当设置账号密码的时候

### ISSUE THREAD

**Issue by wjsw1781** [go-gost/gost#283]
D:/proxy_proxy/gost.exe -L http://:8080 -F socks5://pdlab:pdlab2023@134.73.191.125:9999,socks5://pdlab:pdlab2023@192.200.204.25:9999,socks5://pdlab:pdlab2023@192.200.198.20:9999?strategy=rand&maxFails=1&failTimeout=10s

我的socks代理都需要账号密码认证  但是此时即使成功也总是选取134.73.191.125:9999

我也尝试过
D:/proxy_proxy/gost.exe -L http://:8080 -F socks5://pdlab:pdlab2023@134.73.191.125:9999,192.200.204.25:9999,192.200.198.20:9999?strategy=rand&maxFails=1&failTimeout=10s
结果还是一样

我的版本是最新版本v3

**Comment by wjsw1781** [comment]
![image](https://github.com/go-gost/gost/assets/28215744/070d46d0-f531-43dc-a90b-369884c672a0)

**Comment by ginuerzh** [comment]
```
gost.exe -L http://:8080 -F "socks5://pdlab:pdlab2023@134.73.191.125:9999,192.200.204.25:9999,192.200.198.20:9999?strategy=rand&maxFails=1&failTimeout=10s" -O yaml
```
请提供以上命令的输出信息，应当与下面一致：
```yaml
services:
  - name: service-0
    addr: :8080
    handler:
      type: http
      chain: chain-0
    listener:
      type: tcp
chains:
  - name: chain-0
    hops:
      - name: hop-0
        selector:
          strategy: rand
          maxFails: 1
          failTimeout: 10s
        nodes:
          - name: node-0
            addr: 134.73.191.125:9999
            connector:
              type: socks5
              auth:
                username: pdlab
                password: pdlab2023
            dialer:
              type: tcp
          - name: node-1
            addr: 192.200.204.25:9999
            connector:
              type: socks5
              auth:
                username: pdlab
                password: pdlab2023
            dialer:
              type: tcp
          - name: node-2
            addr: 192.200.198.20:9999
            connector:
              type: socks5
              auth:
                username: pdlab
                password: pdlab2023
            dialer:
              type: tcp
```
