### ISSUE TITLE
grpc 如何自定义host

### ISSUE THREAD

**Issue by f4nff** [go-gost/gost#284]
```
chains:
  - name: chain-0
    hops:
      - name: hop-0
        selector:
          strategy: rand
          maxFails: 1
          failTimeout: 15s
        nodes:           
          - name: node-1
            hosts: hosts-2
            addr: "114.114.114.114:443"
            connector:
              type: relay
              metadata:
                nodelay: "true"
            dialer:
              type: grpc
              metadata:
                  keepalive: true
                  keepalive.time: 8s
                  keepalive.timeout: 8s
                  keepalive.permitWithoutStream: true


# 
 ###       
#日志输出
log:
  output: none
  level: fatal
  format: json
  rotation:
    maxSize: 100
    maxAge: 10
    maxBackups: 3
    localTime: false
    compress: false
 
hosts:
  - name: hosts-1
    mappings:
      - ip: 62.159.160.31
        hostname: "api.gvisor.net"
  - name: hosts-2
    mappings:
      - ip: 2001:19f0:ac01:522:5400:1ff:fe1c:40d6
        hostname: "114.114.114.114"
        
```

            addr: "114.114.114.114:443" 默认了sni,如何自定义host 字段?
