### ISSUE TITLE
socks5 转tun模式配置问题

### ISSUE THREAD

**Issue by novohool** [go-gost/gost#297]
以下配置wintun有起来，但测试curl ifconfig.me 访问不了，ifconfig.me是34.160网段。还有一个问题net那边如果是ipv6需要怎么设置。
```
services:
- name: tun-to-flyme
  addr: ":8421"
  handler:
    type: tun
    chain: chain-0
  listener:
    type: tun
    metadata:
      net: 192.168.123.2/24
      routes:
      - 34.160.0.0/16 192.168.123.2
chains:
- name: chain-0
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      addr: 127.0.0.1:10808
      connector:
        type: socks5

```

**Comment by ginuerzh** [comment]
ping ip能ping通吗，域名是在哪边解析的？

**Comment by novohool** [comment]
> ping ip能ping通吗，域名是在哪边解析的？

tun的可以通，34.160.0.0/16段的，本来可以通的，开了route走代理就不通了。
ping ipconfig.me能显示ip，但无法连接。
```
ping 192.168.123.2

正在 Ping 192.168.123.2 具有 32 字节的数据:
来自 192.168.123.2 的回复: 字节=32 时间<1ms TTL=128
来自 192.168.123.2 的回复: 字节=32 时间<1ms TTL=128
来自 192.168.123.2 的回复: 字节=32 时间<1ms TTL=128
来自 192.168.123.2 的回复: 字节=32 时间<1ms TTL=128
```

**Comment by novohool** [comment]
使用SwitchyOmega +代理服务socks://127.0.0.1:10808，访问ifconfig.me显示的是ipv6的地址，是不是net部分需要配置成ipv6的

**Comment by ginuerzh** [comment]
上面的配置文件写的有问题，客户端需要指定`forwarder`。

**Comment by novohool** [comment]
> 上面的配置文件写的有问题，客户端需要指定`forwarder`。

不是很明白，看了forwarder，还是不清楚哪里需要做转发，socks5 转tun有example吗

**Comment by ginuerzh** [comment]
参考示例：
https://gost.run/tutorials/tuntap/#_22
```yaml
services:
- name: service-0
  addr: :8421
  handler:
    type: tun
    chain: chain-0
  listener:
    type: tun
    metadata:
      net: 192.168.123.2/24
  forwarder:
    nodes:
    - name: target-0
      addr: :8421
chains:
- name: chain-0
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      addr: SERVER_IP:8443
      connector:
        type: relay
      dialer:
        type: wss
```
