### ISSUE TITLE
metadata信息重复

### ISSUE THREAD

**Issue by liaohongxing** [go-gost/gost#303]
命令
```
./gost -L tun://:8421?net=192.168.123.2/24 -O yaml
```
gost_3.0.0-rc9 输出
```
services:
  - name: service-0
    addr: :8421
    handler:
      type: tun
      metadata:
        net: 192.168.123.2/24
    listener:
      type: tun
      metadata:
        net: 192.168.123.2/24
    metadata:
      net: 192.168.123.2/24
```

文档输出：  https://gost.run/reference/handlers/tun/ 
```
services:
- name: service-0
  addr: ":8421"
  handler:
    type: tun
    metadata:
      bufferSize: 1500
  listener:
    type: tun
    metadata:
      net: 192.168.123.2/24
```

metadata 信息似乎多处重复
