### ISSUE TITLE
Not Able To Expose ttyd Using Reverse Proxy Tunnel.

### ISSUE THREAD

**Issue by Puhanshibani** [go-gost/gost#308]
As a developer wanted to expose ttyd command line tool over the internet. The tunnel creation is established but when trying to access it error saying "ws connection closed."

Error:
[2023/10/21 18:58:57:5384] N: WS   /ws - 18.192.146.6, clients: 2
[2023/10/21 18:58:57:5389] N: WS closed from 18.192.146.6, clients: 1

FYI:
able to expose nginx but not ttyd.

Thank you in advance.

**Comment by ginuerzh** [comment]
Which version do you use?
Please share your configuration.

**Comment by ginuerzh** [comment]
You can also quick test the ttyd service with the docker-compose configuration below:
```yaml
version: '3'

services:
  ttyd: 
    image: tsl0922/ttyd
    restart: always

  gost: 
    image: gogost/gost
    command: "-L rtcp://:0/ttyd:7681 -F tunnel+wss://tunnel.gost.plus:443"
    restart: always
```
See https://gost.run/en/tutorials/reverse-proxy-advanced/#public-reverse-proxy-service for more detail.
