### ISSUE TITLE
反向代理命令行参数问题

### ISSUE THREAD

**Issue by Y4er** [go-gost/gost#310]
```
gost.exe -V
gost 3.0.0-rc9 (go1.21.1 windows/amd64)
```
A机器需要起2个gost进程
```
.\gost.exe -L socks5://:9191
.\gost.exe -L rtcp://:8291/:9191 -F relay+ws://vps:9090
```
vps运行
```
./gost -L relay+ws://:9090?bind=true
```
此时B机器配置socks5 vps:8291端口`curl cip.cc`为A机器ip，配置正确。

但是当A机器将socks和rtcp配置为一条命令时

```
.\gost.exe -L socks5://:9191 -L rtcp://:8291/:9191 -F relay+ws://vps:9090
```

代理不生效，`curl cip.cc`为vps ip。

想知道如何一条命令在A机器上开启socks代理并转发到vps的8291端口

**Comment by ginuerzh** [comment]
https://gost.run/concepts/service/#_3

```
gost.exe -L socks5://:9191?ignoreChain=true -L rtcp://:8291/:9191 -F relay+ws://vps:9090
```
或者
```
gost.exe -L socks5://:9191 -- -L rtcp://:8291/:9191 -F relay+ws://vps:9090
```

也可以使用配置文件
```yaml
services:
  - name: service-0
    addr: :9191
    handler:
      type: socks5
    listener:
      type: tcp
  - name: service-1
    addr: :8291
    handler:
      type: rtcp
    listener:
      type: rtcp
      chain: chain-0
    forwarder:
      nodes:
        - name: target-0
          addr: :9191
chains:
  - name: chain-0
    hops:
      - name: hop-0
        nodes:
          - name: node-0
            addr: vps:9090
            connector:
              type: relay
            dialer:
              type: ws
```
