### ISSUE TITLE
最新版本的Gost使用mwss会产生write: connection reset by peer错误并无法使用

### ISSUE THREAD

**Issue by wangpengsdf** [go-gost/gost#315]
服务器版本：3.0.0_RC10，使用Docker镜像
客户端版版本：3.0.0_RC10，使用Github Release下载的二进制文件
操作系统：Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-153-generic x86_64)
启动命令：
`gost -L='socks5://0.0.0.0:1088' -F 'mwss://example.com:443?path=/jshahshgaMAN&secure=true&serverName=example.com&keepalive=true&ttl=15s'
`
报错内容：

`{"handler":"socks5","kind":"service","level":"error","listener":"tcp","msg":"write tcp 192.168.16.118:38652->172.67.182.80:443: write: connection reset by peer","service":"service-0","time":"2023-10-25T20:40:21.442+08:00"}`

其他环境尝试：
在启动命令，服务器版本，客户端版本不变的情况下，更换为MacOS后没有报错
在启动命令，服务器版本，客户端操作系统不变的情况下，使用上一个3.0.0_RC9版本后没有报错

**Comment by sosoyososo** [comment]
THX. 

**这是一个最新版本已经被解决的问题。**

我之前的版本（gost v3.0.0-nightly.20240916 (go1.22.7 darwin/arm64)） 也有类似的问题，我的配置跟 @rikka-p 不一样，同样贴出来，以备其他人发生一样的情况。

我使用gost的目的非常单一，就是根据域名对http流量做分流。也就是只用了两个功能 proxy+bypass。配置如下：
```
services:
  - name: service-0
    addr: ":1083"
    handler:
      type: http
      chain: chain-0
    listener:
      type: tcp
chains:
  - name: chain-0
    hops:
      - name: hop-0
        nodes:
          - name: node-0
            addr: :1082
            bypass: bypass-0
            connector:
              type: http
            dialer:
              type: tcp
bypasses:
  - name: bypass-0
    whitelist: true
    reload: 10s
    redis:
      addr: 127.0.0.1:6379
      db: 0
      password: *password*
      key: gost:bypasses:bypass-0
```
问题：在mac上使用arc浏览器（chrome也一样），通过gost访问局域网nas，具体是访问部署在nas上的docker音乐服务navidrome。常见报错如下：
```
time="2024-11-15T23:06:28+08:00" level=error msg="write response: read tcp 10.0.0.3:56152->192.168.1.2:49157: use of closed network connection" caller="http/handler.go:461" dst="192.168.1.2:49157" handler=http kind=handler listener=tcp local="127.0.0.1:1083" remote="127.0.0.1:56151" service=service-0 sid=csrm6dtno53hvdefjoq0

time="2024-11-16T19:52:40+08:00" level=error msg="write tcp 127.0.0.1:1083->127.0.0.1:57374: write: connection reset by peer" caller="http/handler.go:318" dst="mail.google.com:443" handler=http kind=handler listener=tcp local="127.0.0.1:1083" remote="127.0.0.1:57374" service=service-0 sid=css8f25no53hvdefjvj0

time="2024-11-13T19:12:44+08:00" level=error msg="write response: read tcp 10.0.0.3:56277->192.168.1.2:49157: read: connection reset by peer" caller="http/handler.go:461" dst="192.168.1.2:49157" handler=http kind=handler listener=tcp local="127.0.0.1:1083" remote="127.0.0.1:56276" service=service-0 sid=csq89olno53hvdefhfkg
```
