### ISSUE TITLE
gost通过私有隧道反向代理内网的MySQL时可能有BUG

### ISSUE THREAD

**Issue by praglody** [go-gost/gost#319]
您好，我在使用 gost 的过程中发现一个问题，有可能是 gost 的 BUG 。使用的gost版本是 `v3.0.0-nightly.20231031` 。

我通过私有隧道反向代理内网的 MySQL 服务，在本地无法通过访问端监听的端口访问内网的MySQL。使用同样的方式代理内网的 redis 、ssh 、http 等服务均可以生效。

我的三端的配置和代理redis 、ssh 、http等服务时没有区别，应该不是我配置的原因，最后会给出我的详细的配置信息。

本地使用 navicat 连接内网的 MySQL 时，navicat 报如下这个错误，使用其它 mysql 客户端也不行。
```txt
2013 - Lost connection to server at 'handshake: reading initial communication packet', system error: 0
```

本地访问端日志没见异常：
```json
{"caller":"local/handler.go:180","dst":"com.for.mysql:0/tcp","duration":29932075446,"handler":"tcp","host":":0","kind":"handler","level":"info","listener":"tcp","local":"127.0.0.1:43306","msg":"127.0.0.1:54662 >-< com.for.mysql","node":"mysql","remote":"127.0.0.1:54662","service":"service-2","time":"2023-11-01T14:18:42.549+08:00"}
{"caller":"local/handler.go:85","dst":"com.for.mysql:0/tcp","duration":29990435964,"handler":"tcp","host":":0","kind":"handler","level":"info","listener":"tcp","local":"127.0.0.1:43306","msg":"127.0.0.1:54662 >< 127.0.0.1:43306","node":"mysql","remote":"127.0.0.1:54662","service":"service-2","time":"2023-11-01T14:18:42.550+08:00"}
```

服务器端日志如下：

```json
{"caller":"tunnel/handler.go:161","handler":"tunnel","kind":"handler","level":"info","listener":"tcp","local":"172.22.136.19:8443","msg":"1.119.140.68:52010 <> 172.22.136.19:8443","node":"85c448ed-efec-4a5f-b8ee-0ce7f71be640","remote":"1.119.140.68:52010","service":"service-0","time":"2023-11-01T14:18:13.572+08:00"}
{"caller":"tunnel/handler.go:169","duration":29930321922,"handler":"tunnel","kind":"handler","level":"info","listener":"tcp","local":"172.22.136.19:8443","msg":"1.119.140.68:52010 >< 172.22.136.19:8443","node":"85c448ed-efec-4a5f-b8ee-0ce7f71be640","remote":"1.119.140.68:52010","service":"service-0","time":"2023-11-01T14:18:43.503+08:00"}
{"caller":"service/service.go:191","handler":"tunnel","kind":"service","level":"error","listener":"tcp","msg":"EOF","service":"service-0","time":"2023-11-01T14:18:43.503+08:00"}
```

内网的客户端从始至终没有输出日志，感觉应该是服务端没有把流量转发给内网的客户端。

### 服务端的配置

```yaml
services:
- name: service-0
  addr: 0.0.0.0:8443
  handler:
    type: tunnel
    metadata:
      ingress: ingress-0
  listener:
    type: tcp
ingresses:
- name: ingress-0
  rules:
  - hostname: "com.for.nvidia.ssh"
    endpoint: $aede1f6a-762b-45da-b937-b6632356555a
  - hostname: "com.for.mysql"
    endpoint: $aede1f6a-762b-45da-b937-b6632356555a
  - hostname: "com.for.redis"
    endpoint: $aede1f6a-762b-45da-b937-b6632356555a
```

### 内网客户端配置

```
services:
- name: service-0
  addr: :0
  handler:
    type: rtcp
  listener:
    type: rtcp
    chain: chain-0
  forwarder:
    nodes:
    - name: nvidia-ssh
      addr: 127.0.0.1:22
      host: com.for.nvidia.ssh
    - name: redis
      addr: 192.168.2.21:30121
      host: com.for.redis
    - name: mysql
      addr: 192.168.2.12:3306
      host: com.for.mysql
chains:
- name: chain-0
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      addr: [my-server-ip]:8443
      connector:
        type: tunnel
        metadata:
          tunnel.id: aede1f6a-762b-45da-b937-b6632356555a
      dialer:
        type: tcp
```

### 本地访问端配置

```yaml
services:
- name: service-0
  addr: 0.0.0.0:46022
  handler:
    type: tcp
    chain: chain-0
  listener:
    type: tcp
  forwarder:
    nodes:
    - name: nvidia-ssh
      addr: com.for.nvidia.ssh
- name: service-1
  addr: 0.0.0.0:46379
  handler:
    type: tcp
    chain: chain-0
  listener:
    type: tcp
  forwarder:
    nodes:
    - name: redis
      addr: com.for.redis
- name: service-2
  addr: 0.0.0.0:43306
  handler:
    type: tcp
    chain: chain-0
  listener:
    type: tcp
  forwarder:
    nodes:
    - name: mysql
      addr: com.for.mysql
chains:
- name: chain-0
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      addr: [my-server-ip]:8443
      connector:
        type: tunnel
        metadata:
          tunnel.id: aede1f6a-762b-45da-b937-b6632356555a
        dialer:
          type: tcp
```

**Comment by ginuerzh** [comment]
mysql比较特殊，连接建立后是服务端先发送数据。tunnel协议是基于relay协议改造而来，客户端默认会等待用户数据，当收到用户请求数据后才会真正建立连接，目的是减少一次数据交互。
在访问端的tunnel connector中可以通过开启`nodelay`选项来立即建立连接。
```yaml
chains:
- name: chain-0
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      addr: [my-server-ip]:8443
      connector:
        type: tunnel
        metadata:
          tunnel.id: aede1f6a-762b-45da-b937-b6632356555a
          nodelay: true
        dialer:
          type: tcp
```
