### ISSUE TITLE
监控指标不知道怎么配置，谁懂啊

### ISSUE THREAD

**Issue by kssion** [go-gost/gost#324]
本地安装了 Grafana，仪表盘有了但是没有数据
有没有懂的指点一下，不知道数据源怎么配置，数据显示不出来
还有 http://127.0.0.1:9000/metrics 这个地址需要配置到哪里，没找到地方

![image](https://github.com/go-gost/gost/assets/12656299/57f7eade-1937-4891-90a4-d2ff47fcdb00)

<img width="1369" alt="image" src="https://github.com/go-gost/gost/assets/12656299/a4b0105a-5720-4b86-a076-87293bde39d9">

**Comment by ginuerzh** [comment]
需要prometheus
#223

**Comment by kssion** [comment]
#223 这个我看过了，最终没有说怎么通过prometheus配置显示数据，prometheus我已经下载并且启动了，但是不知道怎么用，我再去看下文档。

![](https://user-images.githubusercontent.com/12656299/281726744-a4b0105a-5720-4b86-a076-87293bde39d9.png)

**Comment by ginuerzh** [comment]
参考以下`prometheus.yaml`配置：
```yaml
global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
# A list of scrape configurations.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'gost'
    scrape_interval: 5s
    static_configs:
      - targets: ['127.0.0.1:9000']
```
