### ISSUE TITLE
loadbalance to multi-port ( Port Hopping )

### ISSUE THREAD

**Issue by AkramiPro** [go-gost/gost#326]
hi, thank you for awesome program.
I know that you support load balancing.
but i want to load balance on same ip but on different ports.
like 192.168.1.10:20000-50000
because in my country they have some limit on ports so i need to connect to each port randomly
I use hysteria in my remote server and it can accept request on multi-port.
I just need to config gost to transfer traffic on random port in range that i gave him.
can you add this to gost ?

https://v2.hysteria.network/zh/docs/advanced/Port-Hopping/

![image](https://github.com/go-gost/gost/assets/54323929/8cff0f40-7c51-4bbf-b2ac-f74ad79f4c6e)

**Comment by ginuerzh** [comment]
The hysteria port-hopping is a protocol specific feature, and is different from the load balancing on gost hop.

**Comment by AkramiPro** [comment]
thank you for your time and response
yes i know that but i just give some info for you to maybe it help you to understand why i need load balance on port instead of ips
i make example for you :

### currently config:

```
  - name: service-1
    addr: :443
    handler:
      type: tcp
    listener:
      type: tcp
    forwarder:
      selector:
        strategy: round
        maxFails: 1
        failTimeout: 30s
      nodes:
        - name: target-0
          addr: 127.0.0.1:1001
        - name: target-1
          addr: 127.0.0.1:1002
        - name: target-2
          addr: 127.0.0.1:1003
        - name: target-3
          addr: 127.0.0.1:1004
        - name: target-4
          addr: 127.0.0.1:1005
        - name: target-5
          addr: 127.0.0.1:1006
        - name: target-6
          addr: 127.0.0.1:1007
        - name: target-7
          addr: 127.0.0.1:1008
        - name: target-8
          addr: 127.0.0.1:1009
        - name: target-9
          addr: 127.0.0.1:1010
```

### expected config:

```
  - name: service-1
    addr: :443
    handler:
      type: tcp
    listener:
      type: tcp
    forwarder:
      selector:
        strategy: round
        maxFails: 1
        failTimeout: 30s
      nodes:
        - name: target-0
          addr: 127.0.0.1:1001-1010
```
