### ISSUE TITLE
Port range forwarder

### ISSUE THREAD

**Issue by iamfarhad** [go-gost/gost#334]
How can i use range port forwarder?

I cant find any documentation

**Comment by iamfarhad** [comment]
I want like this


gost -L tcp://:8000-8003/192.168.1.1:8000-8003 -F.....

But not working

**Comment by woodlyer** [comment]
like this
```
gost -L tcp://:8000/192.168.1.1:8000  -L tcp://:8001/192.168.1.1:8001 ....   -F 
```

**Comment by iamfarhad** [comment]
i knew that. but i want know about port range forwarder in new version.

i can use port range for v2ray easy

**Comment by woodlyer** [comment]
It's new feature.  Not implemented.
pull request welcome.

**Comment by iamfarhad** [comment]
https://github.com/go-gost/gost/commit/b8383b1076bff9c7c347d63fbce45ae413fd834c

**Comment by woodlyer** [comment]
super fast.

**Comment by iamfarhad** [comment]
@ginuerzh

**Comment by iamfarhad** [comment]
@ginuerzh when gost will be support full port range?

**Comment by ginuerzh** [comment]
Now you can use `gost -L tcp://:8000-8003/192.168.1.1:8000-8003` to map port 8000-8003 to 192.168.1.1:8000-8003 in the latest version.
It is equivalent to the following configuration
```yaml
services:
  - name: service-0
    addr: :8000
    handler:
      type: tcp
    listener:
      type: tcp
    forwarder:
      nodes:
        - name: target-0
          addr: 192.168.1.1:8000
  - name: service-1
    addr: :8001
    handler:
      type: tcp
    listener:
      type: tcp
    forwarder:
      nodes:
        - name: target-1
          addr: 192.168.1.1:8001
  - name: service-2
    addr: :8002
    handler:
      type: tcp
    listener:
      type: tcp
    forwarder:
      nodes:
        - name: target-2
          addr: 192.168.1.1:8002
  - name: service-3
    addr: :8003
    handler:
      type: tcp
    listener:
      type: tcp
    forwarder:
      nodes:
        - name: target-3
          addr: 192.168.1.1:8003
```
