### ISSUE TITLE
tun 模式组网后，服务端没办法连客户端的其它网络吗？也就是客户端开 nat 没用？

### ISSUE THREAD

**Issue by yorks** [go-gost/gost#338]
两边环境都是 linux ,gost 版本：
gost v3.0.0-nightly.20231029 (go1.21.3 linux/amd64)

服务端
```bash
gost -L tun://:8421?net=10.10.10.1/24&name=tungost -L relay+ws://127.0.0.80:8080?auth=***&bind=true
# nginx
proxy_pass http://127.0.0.80:8080;
# 开启nat
iptables -t nat -A POSTROUTING -s 10.10.10.0/24 ! -d 10.10.10.0/24 -j MASQUERADE
# 打开转发
sysctl -w net.ipv4.ip_forward=1
iptables -I FORWARD -s 10.10.10.0/24 -j ACCEPT
```

客户端
```bash
gost -L tun://:0/:8421?net=10.10.10.3/24&name=tun2jp&keepAlive=true -F relay+wss://gost.server.domain:443?auth=****
# 开启nat
iptables -t nat -A POSTROUTING -s 10.10.10.0/24 ! -d 10.10.10.0/24 -j MASQUERADE
# 打开转发
sysctl -w net.ipv4.ip_forward=1
iptables -I FORWARD -s 10.10.10.0/24 -j ACCEPT

```

验证：

1. 先验证 服务端的 nat 功能，正常。

   ```bash
   # 在客户端ping 
   [root@yypc ~]# ping 10.10.10.1
   PING 10.10.10.1 (10.10.10.1) 56(84) bytes of data.
   64 bytes from 10.10.10.1: icmp_seq=1 ttl=127 time=58.2 ms
   64 bytes from 10.10.10.1: icmp_seq=2 ttl=127 time=58.3 ms
   # 指定路由走服务端
   [root@yypc ~]# ip r add 1.1.1.3 via 10.10.10.1  
   [root@yypc ~]# ping 1.1.1.3 
   PING 1.1.1.3 (1.1.1.3) 56(84) bytes of data.
   
   # 在服务端抓包，发现能抓到。
   [root@ip-172-31-47-10 ~]# tcpdump -i any -nnnn -vv host 1.1.1.3
   tcpdump: data link type LINUX_SLL2
   dropped privs to tcpdump
   tcpdump: listening on any, link-type LINUX_SLL2 (Linux cooked v2), snapshot length 262144 bytes
   06:27:43.698939 tungost In  IP (tos 0x0, ttl 64, id 1849, offset 0, flags [DF], proto ICMP (1), length 84)
   ```

2. 反过来，验证 客户端 nat 功能，不行！！！

   ```bash
   # 服务端 ping 跟设置 路由
   [root@ip-172-31-47-10 ~]# ping 10.10.10.3
   PING 10.10.10.3 (10.10.10.3) 56(84) bytes of data.
   64 bytes from 10.10.10.3: icmp_seq=1 ttl=64 time=63.1 ms
   64 bytes from 10.10.10.3: icmp_seq=2 ttl=64 time=1044 ms
   64 bytes from 10.10.10.3: icmp_seq=3 ttl=64 time=58.1 ms
   ^C
   --- 10.10.10.3 ping statistics ---
   4 packets transmitted, 3 received, 25% packet loss, time 3042ms
   rtt min/avg/max/mdev = 58.059/388.355/1043.931/463.566 ms, pipe 2
   [root@ip-172-31-47-10 ~]# ip r add 1.1.1.2 via 10.10.10.3
   [root@ip-172-31-47-10 ~]# ping 1.1.1.2 
   PING 1.1.1.2 (1.1.1.2) 56(84) bytes of data.
   
   # 客户的抓不到包
   [root@yypc swap]# tcpdump -i any -n -vvv icmp and host 1.1.1.2
   tcpdump: data link type LINUX_SLL2
   tcpdump: listening on any, link-type LINUX_SLL2 (Linux cooked v2), snapshot length 262144 bytes
   ^C
   0 packets captured
   0 packets received by filter
   0 packets dropped by kernel
   
   ```

edited@20231117 15:16:00
大概知道啥问题，貌似是 一定要服务端指定 route 参数。 用 ip route add 的方式行不通。

**Comment by ginuerzh** [comment]
服务端需要通过`routes`参数设置路由表https://gost.run/tutorials/tuntap/#_7 否则服务端不知道流量要转发到哪个客户端。
具体示例可以参考https://gost.run/blog/2022/tun/

**Comment by yorks** [comment]
> 服务端需要通过`routes`参数设置路由表https://gost.run/tutorials/tuntap/#_7 否则服务端不知道流量要转发到哪个客户端。 具体示例可以参考https://gost.run/blog/2022/tun/

 我看了，我的意思是，都组网成功了， 利用系统的路由功能（ip route add 的方式指定gw （某个客户端）） 这样方便做策略路由啊，因为ip是不固定的。

**Comment by yorks** [comment]
或者 routes 的参数 能否动态添加？

**Comment by ginuerzh** [comment]
TUN服务端不依赖于系统路由表来路由，后面会将路由表独立为单独的组件。

**Comment by ginuerzh** [comment]
路由表已可以独立使用和管理
https://latest.gost.run/concepts/router/

**Comment by yorks** [comment]
> 路由表已可以独立使用和管理 https://latest.gost.run/concepts/router/

弱弱问一下 命令行怎么写这两个参数，我试过 `&routers.file.path=/etc/gost/routers&routes.reload=10s` 这样不生效。
因为我是利用 systemctl 去执行不同的命令行来启动服务，没有细看配置文件的方式。

**Comment by yorks** [comment]
> 路由表已可以独立使用和管理 https://latest.gost.run/concepts/router/

没生效啊？

```yaml
services:
  - name: service-0
    addr: :8421
    handler:
      type: tun
      metadata:
        gw: 10.10.10.3
        name: tungost
        net: 10.10.10.1/24
        route: 192.168.14.0/24
    listener:
      type: tun
      metadata:
        gw: 10.10.10.3
        name: tungost
        net: 10.10.10.1/24
        route: 192.168.14.0/24
    metadata:
      gw: 10.10.10.3
      name: tungost
      net: 10.10.10.1/24
      route: 192.168.14.0/24
  - name: service-1
    addr: 127.0.0.80:8080
    handler:
      type: relay
      auth:
        username: gost
        password: ××××××
      metadata:
        bind: "true"
    listener:
      type: ws
      metadata:
        bind: "true"
    metadata:
      bind: "true"
routers:
- name: router-0
  reload: 10s
  file:
    path: /etc/gost/routes
```
```bash
[root@ip-172-31-47-10 gost]# /usr/bin/gost -V
gost v3.0.0-nightly.20231120 (go1.21.4 linux/amd64)
[root@ip-172-31-47-10 gost]# cat /etc/gost/routes
1.1.1.3/32  10.10.10.3
[root@ip-172-31-47-10 gost]# ip r | grep 10.10.10.3
192.168.14.0/24 via 10.10.10.3 dev tungost 
[root@ip-172-31-47-10 gost]# ip r get 1.1.1.3
1.1.1.3 via 172.31.32.1 dev enX0 src 172.31.47.10 uid 0 
    cache 
# 尝试自己加路由，
[root@ip-172-31-47-10 gost]# ip r add 1.1.1.3 via 10.10.10.3
[root@ip-172-31-47-10 gost]# ping 10.10.10.3
PING 10.10.10.3 (10.10.10.3) 56(84) bytes of data.
64 bytes from 10.10.10.3: icmp_seq=1 ttl=64 time=108 ms
^C
--- 10.10.10.3 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 108.184/108.184/108.184/0.000 ms
[root@ip-172-31-47-10 gost]# ping 1.1.1.3
PING 1.1.1.3 (1.1.1.3) 56(84) bytes of data.

# 客户抓包还是没有
```
