### ISSUE TITLE
负载均衡算法优化建议

### ISSUE THREAD

**Issue by f4nff** [go-gost/gost#340]
```
        selector:
          strategy: fifo
          maxFails: 2
          failTimeout: 30s
```
这是目前的负载均衡,根据发起请求是否死亡作为链路的评定标准,但是如果一个链路出现丢包的时候,
体验会急剧下降,这时候需要转移节点.

以grpc协议为例,应该加一个最大延时的判断基准,以grpc ping的延时作为基准,

```
        selector:
          strategy: fifo
          maxFails: 2
          failTimeout: 30s
          pingtime: 250ms

```

当ping的延时大于预设的250ms标记为节点死亡.
这样可以最大程度的反馈出当前链路的质量,并且快速的转移到优质备用节点.
