### ISSUE TITLE
多网卡多IP服务器 如何实现根据入口IP自动获取对应的网卡出?

### ISSUE THREAD

**Issue by luoye25285** [go-gost/gost#341]
https://gost.run/tutorials/multi-homed/
文档里有指定 interface

如何根据入口IP所绑定的interface自动设置,实现入口IP和出口IP的一致?

**Comment by ZhiShengYuan** [comment]
你可以参考 `Linux 源进源出` 的文章进行实现。

**Comment by chuncui0207** [comment]
同问+1

**Comment by ginuerzh** [comment]
This is now implemented via commit go-gost/x@504c56f.

A new special value `interface: "auto"` enables per-connection interface auto-detection on multi-homed hosts. When a connection arrives on a specific IP, the outbound socket is automatically bound to the same IP, ensuring egress traffic leaves via the same interface that received the inbound connection (the 源进源出 pattern).

**Usage example:**

```yaml
services:
  - name: multi-homed-proxy
    addr: ":8080"
    handler:
      type: http
    listener:
      type: tcp
    metadata:
      interface: auto
```

Comma-separated interface lists with fallbacks are also supported, e.g. `interface: "auto,eth1"` will try the ingress interface first, then fall back to `eth1`.

**How it works:** The router reads the ingress IP from the connection context (set as `DstAddr` from `conn.LocalAddr()` when the connection is accepted), resolves it to the corresponding network interface, and binds the outbound socket using the same `bindDevice` / `LocalAddr` mechanism as the static `interface` option already uses.
