### ISSUE TITLE
寻求GOST插件系统实现粘性会话的指导

### ISSUE THREAD

**Issue by Aubermean** [go-gost/gost#347]
我正在尝试使用GOST插件系统实现基于用户名中会话ID的粘性会话。我的目标是根据用户名中的会话ID维持特定IP的持续性，如果60秒内没有收到请求，则会话将获得新的IP。我注意到插件系统似乎不支持自定义哈希选择器，因此在深入研究之前，我想咨询一下最佳实践。请问，实现此功能的最佳方式是什么？非常感谢您的指导和帮助。

**Comment by zhfish** [comment]
mark

**Comment by ginuerzh** [comment]
你需要用到哪一种插件？没有明白你所说的会话ID粘性的逻辑。

**Comment by wjsw1781** [comment]
相同的用户 id 最终跳跃点出口 ip 是一样的  我想了想必须改动选择器 接受认证器判定的用户 id 才行 但是我没学过不会写 go
作者这个违背你的理念吗 我也有这个需求 但是我不会写

**Comment by wjsw1781** [comment]
我尝试学了下 go 语法 从不违背您的设计调度 出发  我觉得得这么设计 大佬您看看对吗 


func (s *hashStrategy[T]) Apply(ctx context.Context, vs ...T) (v T) {
	if len(vs) == 0 {
		return
	}

	// --- 新增逻辑开始 ---
	// 尝试从 Context 中获取认证器存入的 ClientID (即用户 ID)
	if clientID := metadata.ContextKeyClientID.GetValue(ctx); clientID != nil {
		if idStr, ok := clientID.(string); ok && idStr != "" {
			value := uint64(crc32.ChecksumIEEE([]byte(idStr)))
			logger.Default().Tracef("hash by user-id: %s %d", idStr, value)
			return vs[value%uint64(len(vs))]
		}
	}
	// --- 新增逻辑结束 ---

	// 原有的逻辑：获取从 Handler 传下来的 Hash 对象 (通常是 IP 或 Host)
	if h := xctx.HashFromContext(ctx); h != nil {
		value := uint64(crc32.ChecksumIEEE([]byte(h.Source)))
		logger.Default().Tracef("hash %s %d", h.Source, value)
		return vs[value%uint64(len(vs))]
	}

	// 如果既没有 ID 也没有 Hash 对象，退化到随机选择
	s.mu.Lock()
	defer s.mu.Unlock()

	return vs[s.r.Intn(len(vs))]
}

**Comment by wjsw1781** [comment]
需求是这样的  我给手机挂代理 进入 gost ,gost 的跳跃点有 100 个代理 此时只会导致手机的请求一直在变动 前后两次的请求使用不同的跳跃点 无法控制 
如果基于 hash 基于客户端 ip 进行 hash ,这个手机始终只能使用一个出口节点

**Comment by wjsw1781** [comment]
<img width="1294" height="750" alt="Image" src="https://github.com/user-attachments/assets/17742816-2c93-41c5-b1b4-1c2e3bed5fcc" />

**Comment by wjsw1781** [comment]
关于在 GOST v3 中引入基于 ClientID 哈希实现长效粘性会话的建议
1. 现状痛点：为什么现有的 Hash 策略在移动端“不可用”？

目前 GOST v3 的 hash 策略主要依赖 Handler 提供的 ClientAddr（客户端地址）：

连接级的散布而非会话级：ClientAddr 默认包含 IP:Port。在现代浏览器中，打开一个网页会同时发起十几个 TCP 连接，每个连接的源端口（Port）都是随机的。这导致同一个用户在同一秒内的请求，会被 Hash 算法散布到不同的出口节点上。
出口 IP 乱跳：对于 TikTok、Facebook 或电商养号等业务，这种“由于端口变动导致的出口 IP 乱跳”会直接触发风控封号。
移动网络切换：手机在 4G/5G 基站间切换或 WiFi/流量切换时，源 IP 必然改变。现有的哈希策略会让用户的出口 IP 瞬间发生偏移。
2. 核心逻辑：锚点选错了

在代理路由中，只有**“身份（你是谁）”**才是唯一稳定的锚点。

基于 IP 哈希：在 K8s 或大型企业 NAT 环境下，几百人共用一个出口 IP，会导致严重的负载不均。
基于 Host 哈希：同一个用户访问不同网站走不同出口，无法实现设备级的固定出口。
基于 User-ID 哈希（我的方案）：真正实现 "One User = One Fixed Exit IP"。
3. 为什么基于 ClientID 的 Hash 是终极方案？

既然 GOST v3 已经通过认证器将 ClientID 存入 Context，我们应该物尽其用：

绝对的粘性：无论手机怎么切换网络，只要账号（ID）不变，Hash 结果就永远锁定在同一个出口节点。
完美的负载均衡：即便 1000 个用户来自同一个 K8s 内部 IP，只要他们的 ID 不同，流量就能精准地均匀分布到 100 个出口上。
极低的开销：相比于挂载一个外部 HTTP 分流插件，原生支持 hash(id) 算法在内存中完成，是纳秒级的处理，性能和稳定性极高。
4. 方案设计建议

我们可以让 hash 策略优先尝试从 metadata.ContextKeyClientID 获取数据，如果是非认证用户，再降级回现有的 ClientAddr 逻辑。

伪代码逻辑：

go
// 优先：身份哈希（实现设备级长效固定）
if clientID := metadata.ContextKeyClientID.GetValue(ctx); clientID != nil {
    if idStr, ok := clientID.(string); ok && idStr != "" {
        value := uint64(crc32.ChecksumIEEE([]byte(idStr)))
        return vs[value % uint64(len(vs))]
    }
}

// 兜底：现有的 IP/Host 哈希
if h := xctx.HashFromContext(ctx); h != nil {
    value := uint64(crc32.ChecksumIEEE([]byte(h.Source)))
    return vs[value % uint64(len(vs))]
}

我不希望为了一个简单的“固定 IP”需求去额外维护一个 Python 脚本或插件。既然 id 已经在 Context 里了，让选择器原生支持它，是补齐 GOST v3 身份识别路由能力的最后一块拼图。希望大佬能考虑这个建议！

**Comment by ginuerzh** [comment]
@Aubermean @wjsw1781 This feature has been implemented in GOST v3. The hash strategy already supports ClientID-based sticky sessions — when you use the `strategy: hash` selector with an authenticator configured, the hash selector **prioritizes the authenticated user identity (`ClientID`)** over the client IP. Here's how it works end-to-end:

### How it works

**1. Hash strategy priority** ([x/selector/strategy.go](https://github.com/go-gost/x/blob/master/selector/strategy.go)):

```go
func (s *hashStrategy[T]) Apply(ctx context.Context, vs ...T) (v T) {
    // Priority 1: Hash on authenticated ClientID (user identity)
    if clientID := xctx.ClientIDFromContext(ctx); clientID != "" {
        value := uint64(crc32.ChecksumIEEE([]byte(string(clientID))))
        return vs[value%uint64(len(vs))]
    }

    // Priority 2: Hash on hash source (client IP, or host if configured)
    if h := xctx.HashFromContext(ctx); h != nil {
        value := uint64(crc32.ChecksumIEEE([]byte(h.Source)))
        return vs[value%uint64(len(vs))]
    }

    // Priority 3: Random fallback
    return vs[s.r.Intn(len(vs))]
}
```

**2. Authenticated handlers automatically set ClientID in the context after authentication:**

| Handler | Mechanism |
|---------|-----------|
| HTTP / HTTP2 | Basic/Digest proxy auth → `ContextWithClientID(username)` |
| SOCKS4 / SOCKS5 | SOCKS username/password auth → `ContextWithClientID(clientID)` |
| Relay, Tunnel, Router, MASQUE | All propagate ClientID from their authentication |

**3. Even without authentication, the default hash source is already the client IP *without port*** ([service/service.go](https://github.com/go-gost/x/blob/master/service/service.go#L284-L288)) — so one device always gets the same egress node even without auth.

### How to configure

```yaml
services:
  - name: service-0
    addr: :8080
    handler:
      type: http        # or socks5, socks4, etc.
      auther: myauth    # <-- authentication is required for ClientID sticky hash
    listener:
      type: tcp

chains:
  - name: chain-0
    hops:
      - name: hop-0
        selector:
          strategy: hash   # <-- use hash strategy for sticky sessions
        nodes:
          - name: node-0
            addr: proxy1.example.com:8080
          - name: node-1
            addr: proxy2.example.com:8080
          # ... add as many nodes as you need

authers:
  - name: myauth
    auths:
      - username: user1
        password: pass1
      - username: user2
        password: pass2
```

With this configuration:
- **`user1` always gets the same egress node** (e.g., always `proxy1`)
- **`user2` always gets the same egress node** (e.g., always `proxy2`)
- Even if `user1` switches from WiFi to 5G, the hash result stays the same since it's based on username, not IP

### Verification

You can verify it's working by checking the trace logs — set `log.level: trace` and you'll see:
```
hash client user1 3847862314
```
