### ISSUE TITLE
socks5认证异常

### ISSUE THREAD

**Issue by xingcxb** [go-gost/gost#351]
curl使用socks5不携带用户名和密码进行访问的时候无问题；但使用指纹浏览器后就会提示连接失败。如果在配置文件中剔除了handle下的auther: auther-0信息后，不使用账户密码就正常了，但使用了用户名和密码就提示连接失败
断点调试后发现在`ReadUserPassRequest`中的n, err := io.ReadAtLeast(r, b[:], 5)出现了eof

**Comment by xingcxb** [comment]
配置文件如下：
``` yml
services:
  - name: service-0
    addr: ":56789"
    handler:
      type: socks5
      auther: auther-0
    listener:
      type: tcp
authers:
- name: auther-0
  auths:
    - username: root
      password: 123456
```

![gostb2](https://github.com/go-gost/gost/assets/866409/d6aadee9-2299-4d3b-b4d0-35935414184b)
![gostb1](https://github.com/go-gost/gost/assets/866409/5e5dc879-1212-429a-b908-bffe12e7fd2d)


当我去掉配置文件中的`auther: auther-0` 时就正常了

``` yml
services:
  - name: service-0
    addr: ":56789"
    handler:
      type: socks5
    listener:
      type: tcp
authers:
- name: auther-0
  auths:
    - username: root
      password: 123456
```

![gostb3](https://github.com/go-gost/gost/assets/866409/06186135-e6ed-4f15-b761-331c18ff25fd)
