### ISSUE TITLE
[Q] How do I force gost to connect using IPv6 when both are available?

### ISSUE THREAD

**Issue by NightMachinery** [go-gost/gost#359]
I am proxying my domain through Cloudflare, and the domain has both IPv4 and IPv6 enabled. I can also obtain the IPv6 address using `dig AAAA example.com`. But I don't know how I can make `gost` use IPv6.

Using:
```
gost -L=http://:3198 -F=relay+mwss://user:pass@x:x:x::x:x
```
causes an error.

**Comment by char8x** [comment]
the format should be `[ipv6 address]:port`, assume your address is `2606:4700:4700::1111`, port is `443`

```sh
gost -L=http://:3198 -F "relay+mwss://user:pass@[2606:4700:4700::1111]:443"
```

**Comment by NightMachinery** [comment]
@char8x Thanks! 

How do I force it to read the IPv6 from the DNS records of the given domain? The reason I want to do this:
1. The IPs are assigned by Cloudflare and they change.
2. Using IPv6 is more censorship-resistant according to rumours.

I.e., I want sth like
```
gost -L=http://:3198 -F "relay+mwss://user:pass@example.com[FORCE_IPv6]:443"
```

**Comment by char8x** [comment]
Checkout this section [Gost](https://gost.run/en/concepts/resolver/#prefer-ipv6)

```yaml
services:
- name: service-0
  addr: ":8080"
  resolver: resolver-0
  handler:
    type: http
  listener:
    type: tcp

resolvers:
- name: resolver-0
  nameservers:
  - addr: 1.1.1.1
    prefer: ipv6 # default is ipv4
```

You may need to convert the configuration file to yaml format first, and then add the resolver option to your service
