### ISSUE TITLE
ssu无法自动内存回收，内存无限暴涨

### ISSUE THREAD

**Issue by wwng2333** [go-gost/gost#363]
![image](https://github.com/go-gost/gost/assets/17147265/a350ae81-9e57-41df-9f5a-cfab78314f86)
如题，服务端和客户端出现这种情况，客户端运行12h以后，占用600MB内存，服务端直接触发oom重启了

版本：客户端
```bash
root@crazy:~# gost -V
gost v3.0.0-nightly.20231116 (go1.21.3 linux/amd64)
```
服务端
```bash
localhost:~# gost -V
gost v3.0.0-nightly.20231123 (go1.21.4 linux/amd64)
```
配置文件如下:
客户端config:
```yaml
services:
  - name: service-0
    addr: :10053
    handler:
      type: udp
      chain: chain-0
    listener:
      type: udp
    forwarder:
      nodes:
        - name: target-0
          addr: 94.140.14.14:53
chains:
  - name: chain-0
    hops:
      - name: hop-0
        nodes:
          - name: node-0
            addr: hostname:10001
            connector:
              type: ssu
              auth:
                username: chacha20-ietf-poly1305
                password: "password"
              nodelay: true
            dialer:
              type: udp
```
服务端：
```yaml
services:
  - name: service-1-udp
    addr: "[::]:10001"
    resolver: resolver-0
    handler:
      type: ssu
      auth:
        username: chacha20-ietf-poly1305
        password: "password"
    listener:
      type: udp
resolvers:
- name: resolver-0
  nameservers:
  - addr: "udp://127.0.0.1:53"
    prefer: ipv6
    async: true
```
