### ISSUE TITLE
无法使用两个Shaowsocks 组成代理链

### ISSUE THREAD

**Issue by czwstc** [go-gost/gost#38]
故障配置：
```
services:
- name: service-0
  handler:
    type: ss
    chain: chain-0

chains:
- name: chain-0
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      addr: AAAA:8118
      connector:
        type: ss
        auth:
          username: aes-128-gcm
          password: "xxxx"
  - name: hop-1
    nodes:
        - name: node-0
      addr: BBBB:8119
      connector:
        type: ss
        auth:
          username: aes-128-gcm
          password: "xxxx"

```
此时，该service-0 报错：msg="cipher: message authentication failed"

将Hop1 的SS服务器换成 Socks5服务器，
故障消失。
