### ISSUE TITLE
SSHD Tunnel rais error after a period of time

### ISSUE THREAD

**Issue by eloravpn** [go-gost/gost#382]
In cliend i got this error:

`time="2023-12-28T16:04:53Z" level=error msg="ssh: unexpected packet in response to channel open: <nil>" dst=":0/tcp" handler=tcp host=":0" kind=handler listener=tcp local="IP:2096" node= remote="IP:59639" service=service-1`

**it just resolves on restart gost!**

may client config:
```
services:
- name: service-1
  addr: :2096
  climiter: climiter-0
  handler:
    type: tcp
    chain: chain-1
  listener:
    type: tcp
chains:
- name: chain-1
  hops:
  - name: hope-1
    nodes:
    - 
      dialer: 
        auth:
          username: user
          password: pass
        type: sshd
      connector:
        type: sshd
      addr: myserver.ip:2222
      name: node-1
climiters:
- name: climiter-0
  limits:
  - '$$ 1000'
```
My server config:

```
services:
- name: service-1
  addr: :2222
  handler:
    type: forward
  listener:
    type: sshd
    metadata:
      backlog: 50000
    auth:
      username: user
      password: pass
  forwarder:
    nodes:
    - name: target-0
      addr: 127.0.0.1:4222

```

**Comment by ginuerzh** [comment]
**Fix:** https://github.com/go-gost/x/commit/c45d271

**Root cause:** The SSHD dialer caches SSH sessions by address and returns them on subsequent calls without verifying the session is still alive. When an SSH session silently dies (NAT timeout, server disconnect, idle TCP drop), `IsClosed()` still returns `false`, so the dead session is returned to the connector. The connector then calls `ssh.Client.Dial()` on the dead connection → `ssh: unexpected packet in response to channel open:`.

**Fix:** Added a `Ping()` health check (SSH keepalive request with timeout) before returning a cached session. If the ping fails, the dead session is evicted and a fresh connection is created. This matches the dead-session eviction pattern already used by the SSH, KCP, QUIC, and ICMP dialers.

**Workaround for your current config** (proactive keepalive to detect dead sessions before they're needed):

```yaml
dialer:
  type: sshd
  auth:
    username: user
    password: pass
  metadata:
    keepalive: true
    ttl: 30s            # keepalive interval
    keepalive.timeout: 15s
    keepalive.retries: 1
```

The fix also makes the health check work even *without* the keepalive goroutine — every `Dial()` verifies the cached session is alive on-demand, falling back to a fresh connection if it's dead.
