### ISSUE TITLE
使用yml配置文件无法启动

### ISSUE THREAD

**Issue by wander3r** [go-gost/gost#402]
gost版本：
```
mark@fred-virtual-machine:/tmp$ ./gost -V
gost 2.11.5 (go1.19.2 linux/amd64)
```

配置内容：
```
mark@fred-virtual-machine:/tmp$ cat a.yml 
services:
- name: service-0
  addr: ":8084"
  handler:
    type: http
  listener:
    type: tcp
```

启动失败：
```
mark@fred-virtual-machine:/tmp$ ./gost -C a.yml 
2024/01/25 13:46:18 main.go:53: invalid character 's' looking for beginning of value
```
