### ISSUE TITLE
无穷无尽的错误输出

### ISSUE THREAD

**Issue by SamuNatsu** [go-gost/gost#419]
## 场景

服务器处于 A 网络，客户端处于 B 网络，两个网络之间有协议过滤器，仅允许通过 Web 相关的协议（HTTP、WS 等）

现在客户端需要访问服务器上的远程桌面端口 3389

## 服务器配置文件

在服务器上开启 65000 端口用于接受 WSS 隧道连接，使用了验证功能

```yaml
services:
- name: wss-tunnel
  addr: :65000
  handler:
    type: auto
    auth:
      username: *****
      password: *****
  listener:
    type: wss
    metadata:
      enableCompression: true
      tls:
        options:
          minVersion: VersionTLS12
          maxVersion: VersionTLS13
```

## 客户端配置文件

在客户端上开启 65000 端口用于接受远程桌面程序的连接，使用转发链将请求最终发送到服务器的 3389 端口

路径为：客户端 65000 --wss--> 服务器 65000 --tcp--> 服务器 3389

```yaml
services:
- name: wss-tunnel
  addr: :65000
  handler:
    type: tcp
    chain: chain-0
  listener:
    type: tcp
  forwarder:
    nodes:
    - name: target-0
      addr: **服务器IP**:3389

chains:
- name: chain-0
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      addr: **服务器IP**:65000
      connector:
        type: socks5
        auth:
          username: *****
          password: *****
      dialer:
        type: wss
        metadata:
          enableCompression: true
        tls:
          options:
            minVersion: VersionTLS12
            maxVersion: VersionTLS13
```

## 结果

客户端可以通过 65000 端口连接到服务器的远程桌面

但是 gost 在运行的过程中会无穷无尽地循环输出 websocket 错误信息：

<img width="1280" alt="image" src="https://github.com/go-gost/gost/assets/49141130/c3f69b2e-f36c-4ff0-9768-9fbe52d00494">

虽然可以正常工作，但是不知道这种东西究竟是如何产生的，是否可能导致某一天服务挂掉
