### ISSUE TITLE
Not accepting more than 1 metadata

### ISSUE THREAD

**Issue by avilabss** [go-gost/gost#425]
I'd like to use gost socks5 with both interface and udp params but I can't because gost seems to only accept the 1st metadata.

Here, gost would only enable udp but ignore the interface:
```
./gost -L socks5://user01:pass01@:8080?udp=true&interface=enx344b50000000
```

Here, gost would bind to the interface but won't enable udp:
```
./gost -L socks5://user01:pass01@:8080?interface=enx344b50000000&udp=true
```

Tried with config file and facing same issue:
Here only udp=true is considered by gost and interface is ignored
```
services:
- name: service-0
  addr: :8080
  handler:
    type: socks5
    auth:
      username: user01
      password: pass01
    metadata:
      udp: true
      interface: enx344b50000000
  listener:
    type: tcp
```
