### ISSUE TITLE
connector = tunnel与dialer = dtls不能搭配使用？

### ISSUE THREAD

**Issue by aa51513** [go-gost/gost#429]
服务端配置
```
services:
- name: service-0
  addr: :1357
  handler:
    type: tunnel
    metadata:
      ingress: ingress-0
  listener:
    type: dtls
ingresses:
- name: ingress-0
  rules:
  - hostname: "ssh.local"
    endpoint: <uuid>
  - hostname: "web.local"
    endpoint: <uuid>
```

访问端配置
```
  services:
  - name: service-ssh
    addr: :2122
    handler:
      type: tcp
      chain: chain-0
    listener:
      type: tcp
    forwarder:
      nodes:
      - name: srv-ssh
        addr: ssh.local
  - name: service-web
    addr: :2180
    handler:
      type: tcp
      chain: chain-0
    listener:
      type: tcp
    forwarder:
      nodes:
      - name: srv-web
        addr: web.local
  chains:
  - name: chain-0
    hops:
    - name: hop-0
      nodes:
      - name: node-0
        addr: 10.0.0.1:1357
        connector:
          type: tunnel
          metadata:
            tunnel.id: <uuid>
          dialer:
            type: dtls
```

错误日志（访问端）
```
{"connector":"tunnel","dialer":"tcp","hop":"hop-0","kind":"dialer","level":"error","msg":"dial tcp 10.0.0.1:1357 : connect: connection refused","node":"node-0","time":"2024-03-18T14:08:30.827+08:00"}
```

看起来像是配置dtls的dialer不起作用，仍然以dialer=tcp去连接，导致连接失败

难道是connector = tunnel与dialer = dtls不能搭配使用？

**Comment by ginuerzh** [comment]
`connector`与`dialer`同属一个级别，你的配置中缩进有问题：
```
  chains:
  - name: chain-0
    hops:
    - name: hop-0
      nodes:
      - name: node-0
        addr: 10.0.0.1:1357
        connector:
          type: tunnel
          metadata:
            tunnel.id: <uuid>
        dialer:
          type: dtls
```
