### ISSUE TITLE
哪些协议可以发送 proxy protocol

### ISSUE THREAD

**Issue by ichenhe** [go-gost/gost#430]
当前使用 Gost 做 tcp 端口转发：

```
./gost -L tcp://:22000/example.com:22000?proxyProtocol=2
```

目标主机 `example.com:22000` 运行 traefik，已启用 proxy protocol:

```yaml
# traefik
entryPoints:
  websecure:
    address: :443
    proxyProtocol:
      insecure: true
```

但是并没有获取到真实客户 IP。

#238 提到 `rtcp` 已支持发送 proxy protocol，请问是 `tcp` 不支持吗？
