### ISSUE TITLE
关于wss数据通道的一些疑问

### ISSUE THREAD

**Issue by Typhonling** [go-gost/gost#431]
1、文档中socks+tls中为了避免双重加密，建议使用notls=true关闭socks5中的tls加密。那么socks+wss是否等同于socks+ws+tls，也建议使用notls=true？
2、wss是否也兼容tls的证书设置，使用如下设置？
```
dialer:
        type: wss
        tls:
          secure: true
```
