### ISSUE TITLE
[Feature Request]socks5请求支持关闭udp的domain unmapping

### ISSUE THREAD

**Issue by zhfish** [go-gost/gost#434]
流量路径： tun2proxy -> gost(socks5) -> socks5_ip
目前用的socks5_ip，在某些客户端上(https://github.com/blechschmidt/tun2proxy) 使用
gost会报
```
{"handler":"auto","kind":"service","level":"error","listener":"tcp","msg":"bad address type","service":"service-0",
"time":"2024-03-24T23:15:37.501+08:00"}   
```

经过一些测试，在sing-box里找到一个开关可以使用
sing-box如果不开开关，也会报错
```
https://sing-box.sagernet.org/zh/configuration/shared/listen

udp_disable_domain_unmapping
如果启用，对于地址为域的 UDP 代理请求，将在响应中发送原始包地址而不是映射的域。
此选项用于兼容不支持接收带有域地址的 UDP 包的客户端，如 Surge。
```

请求帮忙给gost也加上此类开关

**Comment by ginuerzh** [comment]
Added `udp.resolveDomain` (alias `udpResolveDomain`) metadata option to the SOCKS5 handler in [go-gost/x@61eb3e2](https://github.com/go-gost/x/commit/61eb3e2). When enabled, all UDP datagrams sent back to the SOCKS5 client carry IP-typed addresses (ATYP=IPv4 or IPv6) instead of domain-typed addresses (ATYP=0x03), which clients like tun2proxy and Surge cannot parse.

**Usage:**

```yaml
services:
- name: service-0
  addr: ":1080"
  handler:
    type: socks5
    metadata:
      udp: true
      udp.resolveDomain: true
  listener:
    type: tcp
```

**How it works:** A `domainResolvePacketConn` wrapper intercepts `WriteTo` on the client-facing UDP relay and resolves domain addresses to IPs before the SOCKS5 header is encoded. Resolution goes through the router's infrastructure (host mapper → resolver → system DNS). Unresolvable domains are silently dropped rather than forwarded in a format the client would reject.

The option is off by default — existing behavior is unchanged.
