### ISSUE TITLE
请问我这个情况如何修改gost配置档？

### ISSUE THREAD

**Issue by cwyin7788** [go-gost/gost#441]
我现在用的是gost v3版，客户端用小火箭的gost relay，能正常使用，但不是用端口443，服务端配置如下：

```
services:
- name: service-0
  addr: :10099
  handler:
    type: relay
  auth:
      username: admin
      password: password
  metadata:
      knock: private.abc.com
      probeResistance: code:403
  listener:
    type: mwss

```

现在我是用shadow-tls监听443，它可以作为sni proxy，只要客户端域名对，它就会透过sni把请求丢给后面的服务，例如我的Reality监听10090，sni是reality.abc.com，客户端连reality.abc.com，443，shadow-tls就会向后丢给Reality 10090处理，以相同方法我可以在443配置Vision、GRPC、nginx等等

我现在也想令gost（域名gost.abc.com，端口10099）也走443，我想试试Shadow-TLS能不能也把这个gost的sni请求转送去10099的端口？

我上面的gost服务器配置，没有配置sni，我知道gost支持sni，但我不会配置，我已经在v3的教学页面看过怎么配置了，但我还是看不懂，在
handler:
    type: relay

handler已经是relay的情况下，怎么再加入sni？（因为教学网页的例子，handler是sni)，加入了，又怎么在配置档里加上sni.abc.com？教学网页看不懂，我在网上也找不到相关资料，所以才上来发issue请教，不好意思，先谢谢了。

请问我上面的配置档要怎么加入sni和我的域名呢？
