### ISSUE TITLE
v3 版本的 udp 不正常 socks5: UDP relay is disabled

### ISSUE THREAD

**Issue by scruel** [go-gost/gost#478]
gost 作为 client2server 使用，
尝试 server 端命令：
```
gost -L :1080?udp=true
gost -L :1080?relay=udp
gost -L :1080?relay=udp&udp=true
```
三种方式均出现了 `socks5: UDP relay is disabled` 报错。

另外与 sinbox 配合使用 DNS 转发的时候，还有如下的报错，无法解析 DNS 记录：
```
+0000 2024-05-18 20:01:41 DEBUG dns: exchange www.baidu.com. IN A
+0000 2024-05-18 20:12:02 ERROR dns: exchange failed for www.baidu.com. IN A: context canceled
```

关联
https://github.com/go-gost/gost/issues/471
https://github.com/go-gost/gost/issues/274

**Comment by ginuerzh** [comment]
完整的Debug日志有吗？

**Comment by scruel** [comment]
日志只记下了 debug error，当时没完整存下来，有空我复现补一下

**Comment by 189er** [comment]
z:/gost.exe   -D -L socks://127.0.0.7:1080?udp=true&bind=true&relay=udp;
#试了一下udp123,没有问题

**Comment by Naruse-developer** [comment]
我也有这个问题，不过我写的是配置文件，我的配置文件如下
```yaml
services:
- name: service-sosks5
  addr: :8888
  handler:
    type: socks5
    auth:
      username: NjjIKLW7Dqg8dPB62buf
      password: SR4GEpMIOmNKqqg$$$$
  listener:
    type: rtcp
log:
    level: info
    format: json
    output: /root/gost/log
    rotation:
      maxSize: 1000
      maxAge: 30
      maxBackups: 1
      localTime: true
      compress: false
```
这是我的日志

```json
{"cmd":"udp","handler":"socks5","kind":"handler","level":"error","listener":"rtcp","local":"10.138.0.10:8888","msg":"socks5: UDP relay is disabled","remote":"8.8.8.8:55206","service":"service-sosks5","time":"2024-09-04T09:58:49.954Z","user":"NjjIKLW7Dqg8dPB62buf"}
```
