### ISSUE TITLE
414 URI Too Long in telegram-desktop

### ISSUE THREAD

**Issue by cornerot** [go-gost/gost#498]
Hello!

Error 401 when used as an http-proxy in telegram-desktop. Tcpdump output:

```
POST http://149.154.167.41:80/api HTTP/1.1
Host: 149.154.167.41:80
Content-Length: 232
Content-Type: application/x-www-form-urlencoded
Connection: Keep-Alive
Accept-Encoding: gzip, deflate
Accept-Language: ru-RU,en,*
User-Agent: Mozilla/5.0

...

376: HTTP: HTTP/1.1 414 URI Too Long
E...W.@.<..?[..C
BB...........+.P.......HTTP/1.1 414 URI Too Long
Connection: keep-alive
Content-Type: text/html
Server: nginx/0.3.33
Date: Fri, 07 Jun 2024 15:41:49 GMT
Pragma: no-cache
Cache-control: no-store
Content-Length: 175

<html>
<head><title>414 URI Too Long</title></head>
<body bgcolor="white">
<center><h1>414 URI Too Long</h1></center>
<hr><center>nginx/0.3.33</center>
</body>
</html>
```

gost config:

```
services:
- name: service-0
  addr: ":8080"
  handler:
    type: http
    auth:
      username: user1
      password: ********
  listener:
    type: tcp
 ```
 
At the same time, squid works without problems
