### ISSUE TITLE
流量上报间隔可以调整吗？

### ISSUE THREAD

**Issue by wpzzz** [go-gost/gost#503]
默认是5秒，但是大多数情况下不需要这么频繁， 建议设为一个参数，用户可以自定义

**Comment by ginuerzh** [comment]
增加了一个`observePeriod`选项
```
services:
- name: service-0
  addr: ":8080"
  observer: observer-0
  handler:
    type: http
  listener:
    type: tcp
  metadata:
    enableStats: true
    observePeriod: 5s
```
