### ISSUE TITLE
请问配置代理超时时间默认都是10s吗,我配置好后，测试都是等待10s后就返回503了。如何更改呢？配置如下

### ISSUE THREAD

**Issue by sxchxdc** [go-gost/gost#513]
services:
- name: service-0
  addr: ":16666"
  admission: admission-0
  handler:
    type: http
  listener:
    type: tcp
- name: service-1
  addr: ":18888"
  admission: admission-0
  handler:
    type: socks5
  listener:
    type: tcp
admissions:
- name: admission-0
  whitelist: true
  reload: 60s
  file:
    path: /usr/local/etc/admission
log:
  output: /usr/local/etc/agent.log
  level: trace
  format: text

上面是我的配置文件，如果目标服务不可用，超时时间默认是10s，就返回503了。不知道如何更改这个默认设置，timeout，无论我加到哪个位置测试依然是10s。

**Comment by ginuerzh** [comment]
service上新增了`dialTimeout`选项来设置连接建立超时时长:
```
gost -L :16666?dialTimeout=10s
```
或
```yaml
services:
- name: service-0
  addr: ":16666"
  handler:
    type: http
  listener:
    type: tcp
  metadata:
    dialTimeout: 10s
```

今天的nightly版本中可用。
