### ISSUE TITLE
关于v4/v6单独出口问题

### ISSUE THREAD

**Issue by superen7527** [go-gost/gost#530]
关于 https://github.com/go-gost/gost/issues/528 问题

我搭建了本机出口的v4 v6 以及 v4v6混合的池 都用虚拟节点负载随机。

后来测试 对于某些双栈域名 比如 cloudflare.com 正常可以v4和v6单独访问，v4优先，命令行 `curl -6 cloudflare.com`就可以强制指定v6访问，但是我用v6池访问是一直访问失败的`no suitable address found`。
***
比如

```
# 强制使用 IPv4
curl -4 'https://icanhazip.com'
# 强制使用 IPv6
curl -6 'https://icanhazip.com'
```
这些在服务器上都可以返回对应的出口ip

但是
```
cloudflare.com v4为主 可以v6访问
api64.ipify.org v6优先 可v4
```
用v6池无法访问cloudflare
同样 v4池 无法访问上面那个v6优先的地址

又搞了一晚上通宵没搞明白。v4+v6混合的池，并不是我想的那样，随机用v4或者v6。而是v4遇到v6优先的双栈服务器，或者v6遇到v4优先的双栈，都访问不了  
***
日志显示 
```
curl -x socks5://127.0.0.1:665 http://ifconfig.me
curl: (97) Can't complete SOCKS5 connection to ifconfig.me. (3)
```
```
"listener":"tcp","msg":"dial tcp: address [2604:9cc0:1ce8::10]:0: no suitable address found","service":"v6","time":"2024-07-08T03:28:21.337+08:00"
```
和使用的127.0.0.1好像没关系 虽然是v4的本机地址，但是用v6ip访问v6入口的域名没问题。
就是想问一下这种情况，是正常的吗？所有池都是这样，还是我用法有问题有遗漏的部分？

**Comment by ginuerzh** [comment]
对于虚拟节点组的选择，目前没有考虑出口IP与所要访问的目标IP类型一致性。如果目标是ipv4，出口是ipv6或目标是ipv6，出口是ipv4就会访问失败。一种临时性简单的规避方式是采用重试机制(handler.retries)：
```yaml
services:
- name: service-0
  addr: ":8080"
  handler:
    type: auto
    chain: chain-0
    retries: 2
  listener:
    type: tcp
chains:
- name: chain-0
  hops:
  - name: hop-0
    selector:
      strategy: round
    nodes:
    - name: node-0
      addr: :0
      interface: ipv4
      connector:
        type: virtual
      dialer:
        type: virtual
    - name: node-1
      addr: :0
      interface: ipv6
      connector:
        type: virtual
      dialer:
        type: virtual
```

**Comment by ginuerzh** [comment]
你的IP是都在一个网口上还是多网口多IP模式？
如果是多网口，可以直接指定网口名：`interface: eth0`，连接时会自动尝试网口上的所有IP来建立连接。

**Comment by ginuerzh** [comment]
如果是多个双栈网口，直接指定网口就可以了，每个网口上会自动尝试所有IP。如果你是单网口就需要用虚拟节点来做负载均衡，可以每个虚拟节点同时指定ipv4和ipv6来模拟多个双栈网口模式，例如有4个IP：ipv4-1，ipv4-2，ipv6-1，ipv6-2
```yaml
services:
- name: service-0
  addr: ":8080"
  handler:
    type: auto
    chain: chain-0
    retries: 2
  listener:
    type: tcp
chains:
- name: chain-0
  hops:
  - name: hop-0
    selector:
      strategy: round
    nodes:
    - name: node-0
      addr: :0
      interface: ipv4-1,ipv6-1
      connector:
        type: virtual
      dialer:
        type: virtual
    - name: node-1
      addr: :0
      interface: ipv4-2,ipv6-2
      connector:
        type: virtual
      dialer:
        type: virtual
```
这样node-0和node-1虚拟节点就类似于两个双栈网口。
