### ISSUE TITLE
icmp on ipv6 not work

### ISSUE THREAD

**Issue by aa51513** [go-gost/gost#542]
The contents of my configuration file are as follows:
我的配置文件内容如下：

```
services:
- name: service-0
  addr: ":1080"
  handler:
    type: auto
    chain: chain-0
  listener:
    type: tcp
chains:
- name: chain-0
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      addr: ipv6.server.com:0
      connector:
        type: http
      dialer:
        type: icmp
```

The domain `ipv6.server.com` consists of only one AAAA record that resolves to an ipv6 address
ipv6.server.com这个域名只有一条AAAA记录，被解析到一个ipv6地址

The log message only suggests listening on port 1080, after that, there is no other information output, and the icmp channel is not open.
日志信息只提示监听了1080端口，之后就没有其他任何信息输出，icmp通道也没有打通
