### ISSUE TITLE
处理器上的观测器无效, 服务上的观测器可以

### ISSUE THREAD

**Issue by hasikiFire** [go-gost/gost#543]
配置文件：
```
services:
  - name: service-9010
    addr: :9010
    # observer: observer-0 # 服务上的观测器
    handler:
      type: http2
      observer: observer-0
      metadata:
        enableStats: true # 开启统计
        observePeriod: 5s
    listener:
      type: http2
      tls:
        certFile: /etc/gost/fullchain.pem
        keyFile: /etc/gost/privkey.pem
    metadata:
      enableStats: true # 开启统计
      observePeriod: 5s
observers:
  - name: observer-0
    plugin:
      type: http
      addr: http://127.0.0.1:9000/observer
      timeout: 10s

```
如果将 服务上的观测器注释去掉，那就可以监听到服务的，但是  Handler 不行，导致 基于用户标识的流量统计 也无法实现

![image](https://github.com/user-attachments/assets/109b9226-011b-4d86-9760-efcdaeddd3db)

**Comment by hasikiFire** [comment]
暂时方案是每个用户开一个 service，监听不同端口

**Comment by ginuerzh** [comment]
用的哪个版本?

**Comment by hasikiFire** [comment]
> 用的哪个版本?

应该是这版本： gogost/gost:3.0.0-nightly.2024071

**Comment by ginuerzh** [comment]
本地没有复现。

**Comment by hasikiFire** [comment]
方便贴一下你配置吗？我又试了几小时都不行。。

**Comment by ginuerzh** [comment]
在最新的版本中用你提供的配置就可以。

**Comment by hasikiFire** [comment]
经过多次实验，http2 +tls 确实不行。。http+tls 可以，以下为可行配置：
```
services:
- name: service-30002
  addr: :30002
  handler:
    type: http # http2 不行
    auther: auther-0
    limiter: limiter-0
    observer: observer-0
    metadata:
      limiter.refreshInterval: 30s
      enableStats: true # 开启统计
      observePeriod: 5s
  listener:
    type: tls # http2 不行
  metadata:
    knock: www.google.com
    probeResist: file:/var/www/html/index.html
    enableStats: true # 开启统计
    observePeriod: 5s

tls:
  certFile: /etc/gost/fullchain.pem
  keyFile: /etc/gost/privkey.pem
 ```
