### ISSUE TITLE
反向代理隧道Bug

### ISSUE THREAD

**Issue by SianHH** [go-gost/gost#546]
# Bug表现状态
使用反向代理隧道后，暴露内网服务的文件服务后，用Chrome下载文件，在文件下载时中断下载，查看服务端网卡速率，仍然有下行，查看客户端机器网卡占用，发现仍然有上传。
此时正常的网络状态，应该是无大量上传和下载。经测试使用rtcp端口转发无此问题，可以定位为反向代理隧道的bug

# 复现环境：
## 服务器配置：
```yaml
services:
- name: service-0
  addr: :2096
  handler:
    type: tunnel
    metadata:
      entrypoint: ":12096"
      ingress: ingress-0
  listener:
#  listener的type用mwss/wss/ws/mws/quic均有此bug
    type: tcp
ingresses:
- name: ingress-0
  rules:
  - hostname: ".example.com"
    endpoint: 4d21094e-b74c-4916-86c1-d9fa36ea677b
  - hostname: "example.org"
    endpoint: ac74d9dd-3125-442a-a7c1-f9e49e05faca
```

## 客户端配置：
```yaml
services:
- name: service-0
  addr: :0
  handler:
    type: rtcp
  listener:
    type: rtcp
    chain: chain-0
  forwarder:
    nodes:
    - name: target-0
      addr: 127.0.0.1:8080
chains:
- name: chain-0
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      addr: :2096
      connector:
        type: tunnel
        metadata:
          tunnel.id: 4d21094e-b74c-4916-86c1-d9fa36ea677b
          tunnel.weight: 1
      dialer:
        type: tcp
```
