### ISSUE TITLE
socks5中转经常会失效，请问有重试机制吗

### ISSUE THREAD

**Issue by naicha520** [go-gost/gost#552]
![image](https://github.com/user-attachments/assets/2e43723e-8cb9-4b92-b55a-bb8bcab39664)

在实际生产当中，socks5链接经常偶尔失败，并发、阻塞、网卡等原因，请问gost有重试机制吗，如果某条请求转发异常了，可以配置重试次数吗，比如直到成功为止，或者转发失败后的处理

**Comment by ginuerzh** [comment]
可以使用`retries`和`dialTimeout`重试。
```
gost -L ":8080?retries=3&dialTimeout=10s"
```

**Comment by Naruse-developer** [comment]
socks5 udp 怎么开启啊？
下列是配置文件
```yaml
services:
- name: service-sosks5
  addr: :8888
  handler:
    type: socks5
    auth:
      username: 123456
      password: 123456
    metadata:
      udp: true
      udpBufferSize: 4096
      notls: true
  listener:
    type: tcp
```
