### ISSUE TITLE
[Help/Question] How can we make client as a proxy in reverse proxy tunnel ?

### ISSUE THREAD

**Issue by xzycn** [go-gost/gost#553]
As the docs(https://gost.run/tutorials/reverse-proxy-tunnel/) say, the test config as follows:
client side :
```bash
log:
  level: debug
services:
  - name: service-0
    addr: :0
    handler:
      type: rtcp
    listener:
      type: rtcp
      chain: chain-0

chains:
  - name: chain-0
    hops:
      - name: hop-0
        nodes:
          - name: node-0
            addr: [server_ip]:8443
            connector:
              type: tunnel
              metadata:
                tunnel.id: 4d21094e-b74c-4916-86c1-d9fa36ea677b
                tunnel.weight: 1
            dialer:
              type: tcp
```
server side :
```bash
services:
  - name: service-0
    addr: :8443
    handler:
      type: tunnel
      metadata:
        entrypoint: "127.0.0.1:10086"
        ingress: ingress-0
    listener:
      type: tcp

ingresses:
  - name: ingress-0
    rules:
      - hostname: "example.com"
        endpoint: 4d21094e-b74c-4916-86c1-d9fa36ea677b
```

Well, after starting them in each node, we can visit  http://ipinfo.io by **curl -x server_ip:10086 http://example.com**, but https failed with TLS shakehand error. After some investigations, found that entrypoint hanler don't handle connect method expect one case:
```go
if v[0] == relay.Version1 {
		return ep.handleConnect(ctx, xnet.NewBufferReaderConn(conn, br), log)
}
```
some questions:
1 What should we do to make the request from curl as a relay request?
2 Now the entrypoint handler only support HTTP proxy request, could we create a auto type handler(support socks and http) forward the request to entrypoint handler?

In one word, how can we access any websites or applications(TCP or UDP) from server side? Thx.

**Comment by ginuerzh** [comment]
The entrypoint in tunnel handler is a normal HTTP reverse proxy service (not an HTTP proxy), used as a convenient way to access web services, and only accepts normal HTTP requests. For non-HTTP traffic, a separate TCP (or UDP) entrypoint needs to be run.
```yaml
services:
  - name: entrypoint
    addr: :8000
    handler:
      type: tcp
      chain: chain-0
    listener:
      type: tcp
    forwarder:
      nodes:
        - name: target-0
          addr: example.com
chains:
  - name: chain-0
    hops:
      - name: hop-0
        nodes:
          - name: node-0
            addr: :8443
            connector:
              type: tunnel
              metadata:
                tunnel.id: 4d21094e-b74c-4916-86c1-d9fa36ea677b
            dialer:
              type: tcp
```
See https://gost.run/tutorials/reverse-proxy-tunnel/#tcp
