### ISSUE TITLE
私有隧道无法转发UDP流量

### ISSUE THREAD

**Issue by SianHH** [go-gost/gost#569]
最新20240904版本，问题任然存在。

本地测试环境：

### 本地用于测试端口转发的服务
```shell
gost.exe -L file://:8080
```

### 本地的UDP服务
```shell
gost.exe -L relay+quic://:33667
```

### Tunnel服务端配置
```yaml
services:
- name: service-0
  addr: :8443
  handler:
    type: tunnel
    metadata:
      ingress: ingress-0
  listener:
    type: ws
ingresses:
- name: ingress-0
  rules:
  - hostname: "srv-2.local"
    endpoint: $ac74d9dd-3125-442a-a7c1-f9e49e05faca
```

### Tunnel客户端
```shell
gost.exe -L rudp://:0/127.0.0.1:33667 -F tunnel+ws://:8443?tunnel.id=ac74d9dd-3125-442a-a7c1-f9e49e05faca
```

### Tunnel访问端
```shell
gost.exe -L udp://127.0.0.1:16666/srv-2.local -F tunnel+ws://127.0.0.1:8443?tunnel.id=ac74d9dd-3125-442a-a7c1-f9e49e05faca
```
### 测试使用本地端口转发
- 不使用Tunnel转发后的隧道，可以正常转发服务
```shell
gost.exe -L tcp://:8081/127.0.0.1:8080 -F relay+quic://127.0.0.1:33667
```

- 使用Tunnel转发后的隧道，无法正常转发服务
```shell
gost.exe -L tcp://:8081/127.0.0.1:8080 -F relay+quic://127.0.0.1:16666
```

### 将quic协议修改ws/wss等tcp为底层协议，将rudp和udp修改为rtcp和tcp，就可以正常转发服务，经测试，Tunnel私有隧道无法转发UDP流量
