### ISSUE TITLE
在同一个虚拟子接口同时监听 IPv4/IPv6 进行端口转发的一些疑问。

### ISSUE THREAD

**Issue by Zerorigin** [go-gost/gost#571]
我想将 GoSTv3 部署到网关路由器上，网关上有一个虚拟接口 lan 绑定了很多物理设备 ethX，在这个虚拟接口 lan 下通过 vlan 划分了多个虚拟子接口，这些虚拟子接口都有属于自己的一个内网 IPv4 网段和动态的公网 IPv6 子网。
而配置在虚拟子接口的 IPv4 网关是固定的，公网 IPv6 网关是动态的（会定期根据营运商分发的前缀进行自动更新）。

我想通过指定虚拟子接口的形式（通过接口名称或接口对应的固定 IPv4 网关地址），来绑定到指定的私网 IPv4 和 IPv6 网关，我的配置如下，但是我发现 GoST 似乎是在父级虚拟接口 lan 下的所有虚拟子接口的所有 IPv4 和 IPv6 地址（包含不在此虚拟子接口的所有弟子）都进行了监听。

似乎 metadata.interface 的含义和我想的有点不一样，我想了解下有什么配置可以实现我想要的效果么？

```
services:
    - name: service-0
      addr: :12345
      handler:
          type: tcp
          chain: chain-0
      listener:
          type: tcp
      metadata:
          interface: "192.168.56.1!"    # or virt_sub_interface_name

chains:
    - name: chain-0
      hops:
          - name: hop-0
            nodes:
                - name: node-0
                  addr: 1.2.3.4:12345
                  connector:
                      type: relay
                      auth:
                          username: username
                          password: password
                      metadata:
                          nodelay: false
                  dialer:
                      type: tls
                      metadata:
                          nodelay: false

log:
    output: stderr
    level: warn
```

**Comment by Zerorigin** [comment]
会出仅绑定特定进站接口这个特性么？

**Comment by ginuerzh** [comment]
`metadata.interface` is an **outbound-only** option — it binds the sockets GOST opens when *dialing* upstream (through the chain), not the listening socket. So with `addr: :12345` the TCP listener binds the wildcard (`0.0.0.0:12345` / `[::]:12345`), and `metadata.interface` has no effect on it — which matches what you're seeing.

What it actually does: it's applied to the router/dialer, where it pins the source IP (`LocalAddr`) and calls `SO_BINDTODEVICE` on the outbound socket so traffic leaves through the named interface. The trailing `!` means "strict" (don't fall back to other interfaces).

**Workaround for inbound:** bind the listener to a specific IP explicitly:

```yaml
services:
  - name: service-0
    addr: 192.168.56.1:12345   # instead of :12345
```

This pins the listener to that IPv4 address only.

**Not supported today:** binding a listener to an *interface name* so it automatically tracks the interface's addresses (including a dynamic IPv6 prefix). That would need a new listener-side option — e.g. `SO_BINDTODEVICE` on the listening socket, or resolving the interface's addresses into bind addresses. It's a reasonable feature request; happy to look at it if there's interest.
