### ISSUE TITLE
Can we use recorder plugin for one node of chain

### ISSUE THREAD

**Issue by nbg1rp** [go-gost/gost#587]
1. great tool! Much appreciated for the author and team!
2. can we use recorder plugin for one node of chain( name: node-1 in the conf) ? pls check below conf.
3. what I want is use bypasses to split traffic into 2 kinds, direct out or proxy out, and record the outgoing domain correspondingly, is there any better way to reach this goal?

```yaml
services:
- name: service-3000
  addr: "127.0.0.1:3000"
  handler:
    type: http
    chain: chain-3000
  listener:
    type: tcp

- name: service-13000
  addr: "127.0.0.1:13000"
  recorders:
  - name: recorder-zl-all
    record: recorder.service.router.dial.address
  - name: recorder-zl-err
    record: recorder.service.router.dial.address.error
  handler:
    type: http
  listener:
    type: tcp

chains:
- name: chain-3000
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      bypass: bypass-2
      addr: "127.0.0.1:13000"
      connector:
        type: http
      dialer:
        type: tcp
    - name: node-1
      bypass: bypass-1
      addr: ":7890"
      recorders:
      - name: recorder-px-all
        record: recorder.service.router.dial.address
      - name: recorder-px-err
        record: recorder.service.router.dial.address.error
      connector:
        type: http
        auth:
          username: "[user]"
          password: "[pass]"
      dialer:
        type: tcp

recorders:
- name: recorder-zl-all
  redis:
    addr: 123.124.125.126:6379
    db: 1
    password: myredispwd
    key: gg_zl_all
    type: set
- name: recorder-zl-err
  redis:
    addr: 123.124.125.126:6379
    db: 1
    password: myredispwd
    key: gg_zl_err
    type: set
- name: recorder-px-all
  redis:
    addr: 123.124.125.126:6379
    db: 1
    password: myredispwd
    key: gg_px_all
    type: set
- name: recorder-px-err
  redis:
    addr: 123.124.125.126:6379
    db: 1
    password: myredispwd
    key: gg_px_err
    type: set

bypasses:
- name: bypass-1
  reload: 60s
  whitelist: false
  file:
    path: /path/to/file
- name: bypass-2
  reload: 60s
  whitelist: true
  file:
    path: /path/to/file
```
