### ISSUE TITLE
反向代理隧道性能弱

### ISSUE THREAD

**Issue by SianHH** [go-gost/gost#590]
## 问题说明
用rtcp远程端口转发，速率可以达到20Mbps左右，而用tunnel，速率只能达到5Mbps。
不是家宽qos的原因，也不是监听器不同导致的问题，反复测试了其他监听器。都是一样的情况。
（版本：20241002）

> 我用本地内网测试，没发现有什么这个问题，用云服务器测试就有这个问题。如果是配置有问题，麻烦指出一下，谢谢

## 服务端配置
```yml
services:
- name: service-0
  addr: :82
  handler:
    type: tunnel
    metadata:
      entrypoint: ":81"
      ingress: ingress-0
      sniffing: true
  listener:
    type: wss

ingresses:
- name: ingress-0
  rules:
  - hostname: ".example.com"
    endpoint: 4d21094e-b74c-4916-86c1-d9fa36ea677b
```

## 客户端配置
```yml
services:
- name: service-0
  addr: :0
  handler:
    type: rtcp
  listener:
    type: rtcp
    chain: chain-0
  forwarder:
    nodes:
    - name: target-0
      addr: 127.0.0.1:5244
chains:
- name: chain-0
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      addr: x.x.x.x:82
      connector:
        type: tunnel
        metadata:
          tunnel.id: 4d21094e-b74c-4916-86c1-d9fa36ea677b
      dialer:
        type: wss
```

**Comment by SianHH** [comment]
这个问题好像是由于高延迟导致的问题，延迟越高，速率越低。
同样的配置，客户端与服务端延迟200ms左右，速率就能复现所描述的问题，
改为延迟100ms左右的服务器，速率可以提高，但仍然无法达到该服务器使用端口转发进行转发效率的50%。

本地测试时，由于延迟很低，所以无法复现这个问题。

**Comment by ginuerzh** [comment]
你是如何测速的？

**Comment by SianHH** [comment]
本地运行的AList，AList挂载的本地目录，通过AList上传和下载文件

**Comment by SianHH** [comment]
> 本地运行的AList，AList挂载的本地目录，通过AList上传和下载文件

文件上传下载，均使用Chrome进行，无其他软件

我也换过飞牛OS进行传输文件，香港、日本、美国的服务器，gost都使用同样的配置，服务器均开启bbr，端口转发均达可到家宽和服务器带宽的合理速率，反向代理下，服务器延迟越高、速率越低。

并且同一个服务器，端口转发速率有50mbps，而反向代理速率只有5mbps，差异巨大。

**Comment by SianHH** [comment]
我使用Frp的http模式转发，不是tcp，速率正常，并不会像gost一样速率差异如此大。
由于私有隧道也基于tunnel，所以私有隧道的性能也有这个问题

**Comment by ginuerzh** [comment]
rtcp使用的是[xtaci/smux]([github.com/xtaci/smux](https://github.com/xtaci/smux)库来实现多路复用，但对于tunnel处理器，其配置采用的是version 2，其他用的是version 1。
可以尝试改一下mux配置对比测试一下，例如版本退回到version 1(注意：客户端和服务端的参数要一致)，更多参数可以参考https://gost.run/tutorials/protocols/ws/#_2

```yaml
services:
- name: service-0
  addr: :82
  handler:
    type: tunnel
    metadata:
      entrypoint: ":81"
      ingress: ingress-0
      mux.version: 1
```

```yaml
chains:
- name: chain-0
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      addr: x.x.x.x:82
      connector:
        type: tunnel
        metadata:
          tunnel.id: 4d21094e-b74c-4916-86c1-d9fa36ea677b
          mux.version: 1
      dialer:
        type: wss
```

**Comment by SianHH** [comment]
设置mux.version并没有解决这个问题，我这里提供两个上传文件时的windows网卡流量图。

反向代理隧道：
![Snipaste_2024-10-15_13-16-03](https://github.com/user-attachments/assets/93483705-d324-48e3-9b93-02ca71873397)

端口转发：
![Snipaste_2024-10-15_13-17-43](https://github.com/user-attachments/assets/d87179f2-46e7-4c52-ba1a-fce19783442d)

**Comment by SianHH** [comment]
大佬，你无法复现这个问题吗？我可以提供我测试的服务器，或者我可以配合采集一下日志，用于排查这个问题

**Comment by ginuerzh** [comment]
目前测试下来，`mux.maxStreamBuffer`选项对速度影响比较大，可以尝试在两端把此选项的值改大(默认65535)，例如1MB或以上：
```yaml
services:
- name: service-0
  addr: :82
  handler:
    type: tunnel
    metadata:
      entrypoint: ":81"
      ingress: ingress-0
      mux.maxStreamBuffer: 1048576

chains:
- name: chain-0
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      addr: x.x.x.x:82
      connector:
        type: tunnel
        metadata:
          tunnel.id: 4d21094e-b74c-4916-86c1-d9fa36ea677b
          mux.maxStreamBuffer: 1048576
      dialer:
        type: wss
```
相关文章：https://lists.torproject.org/pipermail/anti-censorship-team/2021-July/000185.html
