### ISSUE TITLE
gost http proxy requests go to wrong host when with connection: keep-alive

### ISSUE THREAD

**Issue by sivann** [go-gost/gost#592]
**How to reproduce:**

The following command when using gost just downloads the 1st url, not the 2nd:

```
curl  -L --header 'Proxy-Connection: Keep-Alive' \
http://mirror.ath1.fusioned.net/almalinux/9.4/AppStream/x86_64/os/Packages/freeipmi-1.6.14-2.el9.x86_64.rpm -JO --next http://rpm.repo.onapp.com/repo/centos/6/x86_64/mariadb-10.4/MariaDB-common-10.4.17-1.el6.x86_64.rpm -JO 
```

The above. downloads the 1st file, the 2nd one is just a 404 page 100 bytes file. 

Without gost (unset http_proxy), the above succeeds.

The problem is gost tries to request the 2nd URL (rpm.repo...) from the first host ( mirror.ath1.fusioned.net). The problem goes away with --header "Connection: close" but this is out of our control in most cases.

**Environment**
```
no_proxy=localhost,127.0.0.1
https_proxy=http://localhost:3128
http_proxy=http://localhost:3128
```

**Gost config**
```
services:
  - name: local_proxy
    addr: 127.0.0.1:3128
    handler:
      type: http
    listener:
      type: tcp

log:
  level: trace
  format: json
  output: stderr
```
