### ISSUE TITLE
Relay hysteria2 to a remote server.

### ISSUE THREAD

**Issue by woyin** [go-gost/gost#599]
I hope to use gost to perform port forwarding in order to avoid directly exposing ports.

I have deployed gost on server A, Trojan (port 443) on server B, and Hysteria2 (port 8080) on server C.

How should I configure gost to ensure that I only expose server A and its port while being able to connect to servers B and C?

No matter how I configure the handler and listener, whether it's for TCP or UDP, I cannot get the proxy to work properly.
```
  handler:
    type: ??? # no matter tcp or udp can not work properly
  listener:
    type: ??? # no matter tcp or udp can not work properly
```
