### ISSUE TITLE
指定DNS resolver不生效

### ISSUE THREAD

**Issue by aa51513** [go-gost/gost#6]
v3版本尚未正式发布，所以我用的docker v3版本，版本号是`gost 3.0.0-alpha (go1.17.6 linux/amd64)`
我定义了resolver-0，期望chains—hops—nodes—node—addr中的域名，能到我定义的resolver-0中去解析
实际运行结果是，gost并没有去resolver-0进行域名解析，反而是直接调用操作系统dns地址去解析

我的配置文件如下：
```
resolvers:
- name: **my-resolver**
  nameservers:
  - addr: udp://114.114.114.114:53
    prefer: ipv4
    timeout: 3s
services:
- name: service-0
  addr: ":1080"
  handler:
    type: socks5
    **resolver: my-resolver**
    chain: chain-0
  listener:
    type: tcp
chains:
- name: chain-0
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      **resolver: my-resolver**
      addr: **gost.myserver.com**:443
      connector:
        type: relay
      dialer:
        type: wss
```
我希望域名**gost.myserver.com**去**my-resolver**解析，实际上并不生效
