### ISSUE TITLE
最新版gost无法创建证书,与文档不一致

### ISSUE THREAD

**Issue by revintec** [go-gost/gost#605]
使用 gost_3.0.0-nightly.20241102_darwin_arm64 当前的最新版

单独运行 gost
创建 gost.yaml 并运行 gost, 并运行 gost -C gost.yaml
```
tls:
  validity: 87600h
  commonName: gost.run
  organization: GOST
```
创建 gost.yaml 并运行 gost -C gost.yaml -L socks5+tls://...@:... -F ...

均不能在运行目录自动生成证书,与文档不符
https://gost.run/tutorials/tls/#_1
<img width="724" alt="image" src="https://github.com/user-attachments/assets/91e8fe57-eb6b-4296-b7f4-ead43f66137f">

目录放在 ~/Downloads 下面和放在 ~ 下面都无法生成证书,运行 gost 的终端已被授权访问磁盘上的所有文件
