### ISSUE TITLE
Ability to bind API/Metrics to a unix socket

### ISSUE THREAD

**Issue by dumbasPL** [go-gost/gost#610]
would be nice if we could do something like this:
```yml
api:
  addr: "unix://gostapi.sock"
metrics:
  addr: "unix://gostmetrics.sock"
```

This can then be exposed by some other service (like nginx) without the need to bind to localhost or any other interface.

Useful in shared server scenarios when other users on the system can connect to localhost and bypass whatever reverse proxy sits in front.

**Comment by ginuerzh** [comment]
You can now bind to unix domain socket for API and metrics services in the latest nightly version.
```yaml
api:
  addr: "unix:///var/run/gostapi.sock"
metrics:
  addr: "unix:///var/run/gostmetrics.sock"
```
