### ISSUE TITLE
unix转发不支持指定sock文件路径吗？

### ISSUE THREAD

**Issue by SianHH** [go-gost/gost#611]
我尝试使用以下命令将docker.sock转为tcp服务，无法正常转发docker.sock
```shell
gost -L tcp://:8080 -F unix:///var/run/docker.sock
```

当我将工作目录修改为/var/run/，并运行以下命令，此时的docker.sock才能正常转发
```shell
gost -L tcp://:8080 -F unix://docker.sock
```

**Comment by ginuerzh** [comment]
需要使用配置文件：
```yaml
services:
  - name: service-0
    addr: :8080
    handler:
      type: tcp
      chain: chain-0
    listener:
      type: tcp
chains:
  - name: chain-0
    hops:
      - name: hop-0
        nodes:
          - name: node-0
            addr: /var/run/docker.sock
            connector:
              type: unix
            dialer:
              type: unix
```
