### ISSUE TITLE
反向代理隧道在最新版本使用，无法代理 https 流量

### ISSUE THREAD

**Issue by xinghejd** [go-gost/gost#612]
需求：client 端连接到公网 server；access 端在浏览器上配置 socks5 代理，经由 server，代理到 client 端，最后 client 端转发到源站。
以下配置在[v3.0.0-rc10](https://github.com/go-gost/gost/releases/tag/v3.0.0-rc10) 中可以正常使用，但是更新到v3.0.0-nightly.20241117 后 访问 https 应用就会报错，但是 纯 http 在 client 端手动指定 forwarder 的情况下没问题。
```
{"caller":"service/service.go:247","handler":"tunnel","kind":"service","level":"error","listener":"tcp","msg":"invalid method \"\\x16\\x03\\x01\\x06\\xb7\\x01\\x00\\x06\\xb3\\x03\\x03Dv\\xc2\\xc1\\\"\\x8b\\xcc\\xdf\\xcc\\x1bL\\x8a\\xf9\\x81\\x1c:\\ats0\\xbav3\\xa1%\\x06\\xf5\\x99\\x8f$\\x98%\"","service":"service-0","sid":"csvj690d208s3mh9jf70","time":"2024-11-21T21:18:28.269+08:00"}
```

### server config
```
services:
- name: service-0
  addr: :12345
  handler:
    type: tunnel
    metadata:
      ingress: ingress-0
      entrypoint.id: 9fd6c586-1234-49c1-a03a-d48768516951
  auth:
    username: admin
    password: xxxxxx
  listener:
    type: tcp

ingresses:
- name: ingress-0
  rules:
  - hostname: "*.ok.cn"
    endpoint: ac74d9dd-3125-442a-1234-f9e49e05fac1`
```
### client config
```
services:
- name: service-0
  addr: :0
  handler:
    type: rtcp
  listener:
    type: rtcp
    chain: chain-0

chains:
- name: chain-0
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      addr: server_ip:12345
      connector:
        type: tunnel
        metadata:
          tunnel.id: ac74d9dd-3125-442a-1234-f9e49e05fac1
        auth:
          username: admin
          password: xxxxxx
      dialer:
        type: tcp

```

### access config
```
  services:
  - name: service-0
    addr: :1080
    handler:
      type: socks5
      chain: chain-0
      metadata:
        sniffing: true
    listener:
      type: tcp
  chains:
  - name: chain-0
    hops:
    - name: hop-0
      nodes:
      - name: node-0
        addr: server_ip:12345
        connector:
          type: tunnel
          metadata:
            tunnel.id: 9fd6c586-1234-49c1-a03a-d48768516951
          auth:
            username: admin
            password: xxxxxx
          dialer:
            type: tcp
```
