### ISSUE TITLE
shadowsocks service doesn't work with auther

### ISSUE THREAD

**Issue by naebushi** [go-gost/gost#614]
I'm using latest docker gost image (gost 3.0.0 go1.23.3 linux/amd64) with the following config:

```yaml
# this works fine
services:
- name: service-0
  addr: :443
  handler:
    type: ss
    auth:
      username: chacha20-ietf-poly1305
      password: pass
  listener:
    type: tcp
```

but if i move the auth credentials do the dedicated auther section, i'm getting "bad address type" error when the client tries to use proxy:

```yaml
# this doesn't work:
services:
- name: service-0
  addr: :443
  handler:
    type: ss
    auther: auther-0
  listener:
    type: tcp

authers:
- name: auther-0
  auths:
  - username: chacha20-ietf-poly1305
    password: pass
```

Logs:

```
gost  | {"handler":"ss","kind":"service","level":"info","listener":"tcp","msg":"listening on [::]:443/tcp","service":"service-0","time":""}
gost  | {"client":"client_ip","handler":"ss","kind":"handler","level":"info","listener":"tcp","local":"10.0.0.7:443","msg":"client_ip:25633 <> 10.0.0.7:443","remote":"client_ip:25633","service":"service-0"}
gost  | {"client":"client_ip","handler":"ss","kind":"handler","level":"error","listener":"tcp","local":"10.0.0.7:443","msg":"bad address type","remote":"client_ip:25633","service":"service-0"}
gost  | {"client":"client_ip","handler":"ss","kind":"handler","level":"info","listener":"tcp","local":"10.0.0.7:443","msg":"client_ip:40633 <> 10.0.0.7:443","remote":"client_ip:40633","service":"service-0"}
gost  | {"client":"client_ip","handler":"ss","kind":"handler","level":"error","listener":"tcp","local":"10.0.0.7:443","msg":"bad address type","remote":"client_ip:40633","service":"service-0"}
gost  | {"client":"client_ip","handler":"ss","kind":"handler","level":"info","listener":"tcp","local":"10.0.0.7:443","msg":"client_ip:31203 <> 10.0.0.7:443","remote":"client_ip:31203","service":"service-0"}
gost  | {"client":"client_ip","handler":"ss","kind":"handler","level":"error","listener":"tcp","local":"10.0.0.7:443","msg":"bad address type","remote":"client_ip:31203","service":"service-0"}
gost  | {"client":"client_ip","handler":"ss","kind":"handler","level":"info","listener":"tcp","local":"10.0.0.7:443","msg":"client_ip:12138 <> 10.0.0.7:443","remote":"client_ip:12138","service":"service-0"}
gost  | {"client":"client_ip","handler":"ss","kind":"handler","level":"error","listener":"tcp","local":"10.0.0.7:443","msg":"bad address type","remote":"client_ip:12138","service":"service-0"}
```

Same config works if i change handler.type from `ss` to `socks5`:

```yaml
# this works fine:
services:
- name: service-0
  addr: :443
  handler:
    type: socks5
    auther: auther-0
  listener:
    type: tcp

authers:
- name: auther-0
  auths:
  - username: chacha20-ietf-poly1305
    password: pass
```

What am I doing wrong?
