### ISSUE TITLE
How can I secure the API with username and password? 

### ISSUE THREAD

**Issue by ortonomy** [go-gost/gost#619]
how do add auth to `gost --api ...` ? `gost --help` provides no useful info.

**Comment by ginuerzh** [comment]
https://gost.run/en/tutorials/api/overview/#__tabbed_3_1

**Comment by ortonomy** [comment]
Thanks @ginuerzh!

> Authentication information can be set through the auth or auther options. If the auther option is set, the auth option is ignored.

```yaml
api:
  addr: :18080
  auth:
    username: user
    password: pass
  auther: auther-0
```

this doesn't make much sense to me, though. `auther-0` - what does that mean?
