### ISSUE TITLE
tls options not work well

### ISSUE THREAD

**Issue by passwa11** [go-gost/gost#622]
hey, dude
Thks u works for the great tools!

my config
```
- name: service-0
  addr: :8443
  handler:
    type: http
  listener:
    type: tls
    tls:
      options:
        minVersion: VersionTLS13
        maxVersion: VersionTLS13
```

wireshark captures show it used TLS1.2 before TLS1.3 . it's all right ?

![image](https://github.com/user-attachments/assets/e386332f-4314-43d7-b724-a4a52de4e0bf)
