### ISSUE TITLE
Routing traffic to specific interfaces based on target host with socks5 proxy

### ISSUE THREAD

**Issue by sergerdn** [go-gost/gost#644]
### Summary

I want to configure `gost` to route all outgoing traffic through a default interface (e.g., `10.10.11.200`), while routing traffic to specific domains (e.g., `geo.brdtest.com`) through another interface (e.g., `enp0s3`). 

Despite trying various configurations, I couldn't achieve the expected behavior.

### My Test Configuration

The following configuration is intended to test how chains work based on the target domain. However, it does not work as expected because all traffic is routed via `enp0s3`, and the bypass rules are ignored.

```yaml
services:
  - name: "socks5-6001"
    addr: ":6001"
    handler:
      type: socks5
      chain: chain-0
      metadata:
        udp: true
        udpBufferSize: 4096
    listener:
      type: tcp

chains:
  - name: chain-0
    selector:
      strategy: round
      maxFails: 2
    hops:
      - name: hop-0
        nodes:
          - name: node-1
            bypass: bypass-0
            interface: enp0s3
            connector:
              type: virtual
            dialer:
              type: virtual
          - name: node-2
            bypass: bypass-1
            interface: 10.10.11.200
            connector:
              type: virtual
            dialer:
              type: virtual

bypasses:
  - name: bypass-0
    whitelist: true
    matchers:
      - "geo.brdtest.com"
  - name: bypass-1
    whitelist: true
    matchers:
      - "lumtest.com"
```
