### ISSUE TITLE
[功能请求] 能否加入node组的概念

### ISSUE THREAD

**Issue by imshuai** [go-gost/gost#648]
目前没找到关于node组的配置，是否有计划增加支持？  

举例来说，目前一个hop里面可以配置多个node节点，通过选择器来选择不同的节点使用。但是在配置多个node时，如果connector和dialer的配置都是一样的，需要重复编写N次。  

引入nodeGroup概念后，可以对connector和dialer配置相同的node分到同一组，仅设置一次connector和dialer配置，各个不同node仅需配置不同的addr参数即可，配置文件形如：  
```yaml
hops:
  - name: hop-0
    selector:
      strategy: fifo
      maxFails: 1
      failTimeout: 0s
    nodes:
      - name: node-0
        addr: 1.1.1.1:1080
        connector:
          type: socks5
        dialer:
          type: tcp
    nodeGroup:
      - name: nodeGroup-0
         connector:
           type: relay
         dialer:
           type: tcp
         nodes:
           - name: node-1
             addr: 2.2.2.2:2022
           - name: node-2
             addr: 3.3.3.3:2033
           - name: node-3
             addr: 4.4.4.4:2044
```

**Comment by ginuerzh** [comment]
如果能在现有的结构上简单的扩展就不建议增加新的结构。例如可以定义一种引用类型的节点来共享配置，并可以覆写部分字段
```yaml
nodes:
      - name: node-0
        addr: 1.1.1.1:1080
        connector:
          type: socks5
        dialer:
          type: tcp
      - name: node-1
        ref: node-0
        addr: 1.1.1.1:1080
```
node-1节点通过`ref`字段来引用node-0，与node-0使用相同的配置，并通过覆写`addr`字段来定义自己的地址。

**Comment by imshuai** [comment]
> 如果能在现有的结构上简单的扩展就不建议增加新的结构。例如可以定义一种引用类型的节点来共享配置，并可以覆写部分字段

这是一个很好的方案，期望能增加此功能

**Comment by iBug** [comment]
建议直接使用 YAML 高级操作：

```yaml
junk:
  - &common-socks5
    connector:
      type: socks5
    dialer:
      type: tcp
  - &common-auto
    connector:
      type: auto
    dialer:
      type: tcp

nodes:
  - name: node-0
  	<<: *common-socks5
    addr: 1.1.1.1:1080
  - name: node-1
  	<<: *common-socks5
    addr: 1.1.1.1:1081
```

顶层的 `junk` 可以随便起名字，只要是 gost 不认识的名字就行（事实上 `&` 的 anchor 放在哪里都行，只要定义出现在引用之前就行）。
