### ISSUE TITLE
限速限流没有生效

### ISSUE THREAD

**Issue by HiddenStrawberry** [go-gost/gost#649]
```yaml
# 流量速率限制
limiters:
- name: limiter-0
  limits:
  - '$ 1MB 1MB'
# 请求速率
rlimiters:
- name: rlimiter-0
  limits:
  - $ 10
# 并发连接数
climiters:
- name: climiter-0
  limits:
  - $ 10

# 基础服务配置模板
service_template: &service_base
  listener:
    type: tcp
  limiter: limiter-0
  rlimiter: rlimiter-0
  climiter: climiter-0


# 基础连接器配置
connector_template: &connector_base
  type: ss
  auth:
    username: aes-256-gcm
    password: Ldk

services:
# Socks5 服务
- name: socks5-port-7777
  <<: *service_base
  addr: :7777
  handler:
    type: socks5
    chain: chain-7777
    auths:
    - username: user1
      password: pass1

- name: socks5-port-7778
  <<: *service_base
  addr: :7778
  handler:
    type: socks5
    chain: chain-7778
    auths:
    - username: user1
      password: pass1


# HTTP 服务
- name: http-port-8777
  <<: *service_base
  addr: :8777
  handler:
    type: http
    chain: chain-7777
    auths:
    - username: user1
      password: pass1

- name: http-port-8778
  <<: *service_base
  addr: :8778
  handler:
    type: http
    chain: chain-7778
    auths:
    - username: user1
      password: pass1

# SS 服务
- name: ss-port-9777
  <<: *service_base
  addr: :9777
  handler:
    type: ss
    chain: chain-7777
    auth:
      username: aes-256-gcm  # SS 加密方法
      password: pass1


chains:
- name: chain-7777
  hops:
  - name: hop-7777
    nodes:
    - name: node-7777
      addr: 192.168.0.5:6668
      connector: *connector_base

- name: chain-7778
  hops:
  - name: hop-7778
    nodes:
    - name: node-7778
      addr: 192.168.0.6:6668
      connector: *connector_base

- name: chain-7779
  hops:
  - name: hop-7779
    nodes:
    - name: node-7779
      addr: 192.168.0.7:6668
      connector: *connector_base

```

使用这个配置开启服务，并且使用curl --socks5 101.47.44.34:7777 -U user1:pass1 http://speed.hetzner.de/10MB.bin -o /dev/null请求测试限流策略，限流没有生效。

<img width="857" alt="image" src="https://github.com/user-attachments/assets/276b71bc-e65c-4dd8-9bf1-9e30054fac88" />

<img width="1891" alt="image" src="https://github.com/user-attachments/assets/7f123cec-eddc-40b9-b75a-e844ec3e02e6" />

**Comment by HiddenStrawberry** [comment]
使用官方命令又测试了一下 也没有生效 
`./gost -L ":8080?limiter.in=1KB&limiter.out=1KB&limiter.conn.in=1KB&limiter.conn.out=1KB"`

<img width="1895" alt="image" src="https://github.com/user-attachments/assets/8f3f1630-dc8a-4978-846f-62891907666c" />
<img width="799" alt="image" src="https://github.com/user-attachments/assets/185373d0-b110-4cb8-8760-160437378111" />

**Comment by ginuerzh** [comment]
http://speed.hetzner.de/10MB.bin 这个地址有问题

**Comment by HiddenStrawberry** [comment]
那要怎么测速，我试了google.com 看起来限流也没有生效

**Comment by HiddenStrawberry** [comment]
我使用插件的方式配置了一下，限流还是没有生效，插件服务没有收到gost的请求，插件的代码使用的example中的代码：https://github.com/go-gost/plugin/blob/master/limiter/traffic/example/http/main.go 
gost配置文件为
```
services:
- name: service-0
  addr: ":1111"
  limiter: limiter-0
  handler:
    type: http
  listener:
    type: tcp
- name: limiter-0
  plugin:
    type: http
    addr: http://127.0.0.1:8000/limiter
```

使用curl -x http://{ip}:1111 -o /dev/null https://nbg1-speed.hetzner.com/100MB.bin 请求的时候插件服务没有收到任何请求，同时限流也没有生效。

<img width="542" alt="Image" src="https://github.com/user-attachments/assets/0a407a99-2442-46f8-a6f8-11f3e815a768" />

<img width="827" alt="Image" src="https://github.com/user-attachments/assets/6e34e6b4-1b1a-4ff8-957b-a03cf3b41dbc" />

<img width="1886" alt="Image" src="https://github.com/user-attachments/assets/44c5affc-f244-4672-9a71-562fdae17337" />

**Comment by ginuerzh** [comment]
配置有问题
```yaml
services:
- name: service-0
  addr: ":1111"
  limiter: limiter-0
  handler:
    type: http
  listener:
    type: tcp
limiters:
- name: limiter-0
  plugin:
    type: http
    addr: http://127.0.0.1:8000/limiter
```
