### ISSUE TITLE
限速插件好像有点问题

### ISSUE THREAD

**Issue by SianHH** [go-gost/gost#658]
限速插件在handler上的不生效
服务端配置如下：
```yaml
services:
- name: service-0
  addr: ":6666"
  handler:
    type: relay
    limiter: limiter-0
    auther: auther-0
    metadata:
      bind: true
  listener:
    type: tls

limiters:
- name: limiter-0
  plugin:
    type: http
    addr: http://127.0.0.1:8080/limiter
authers:
- name: auther-0
  plugin:
    type: http
    addr: http://127.0.0.1:8080/auther
```

客户端：
```shell
gost -L rtcp://:18081/:8081 -F relay+tls://:6666
```

修改到service上，插件服务可以接收到请求，但是没有认证器返回的标识
