### ISSUE TITLE
反向代理模式，同时访问微信与企业微信的API接口异常

### ISSUE THREAD

**Issue by Dengpr** [go-gost/gost#659]
```yaml
services:
  - name: https
    addr: :443  # 监听 HTTPS 服务的 443 端口
    handler:
      type: tcp
      metadata:
        sniffing: true
    listener:
      type: tcp
    forwarder:
      nodes:
        - name: weixin-api
          addr: qyapi.weixin.qq.com:443  # 代理 https://qyapi.weixin.qq.com/
          matcher:
            rule: Host(`qyapi.weixin.qq.com`)
        - name: weixin-api
          addr: api.weixin.qq.com:443  # 代理 https://api.weixin.qq.com/
          matcher:
            rule: Host(`api.weixin.qq.com`)
        - name: weixin-api
          addr: weixin.qq.com:443  # 代理 https://weixin.qq.com/
          matcher:
            rule: Host(`weixin.qq.com`)
```
在同一个浏览器访问 https://api.weixin.qq.com/与 https://qyapi.weixin.qq.com/的时候，10多秒过后再次访问 https://api.weixin.qq.com/ 页面会提示【403 Forbidden】，在打开一个新的浏览器又能正常访问。

![Image](https://github.com/user-attachments/assets/dde0f9e5-3f96-46ad-919e-61ed962fc858)
