### ISSUE TITLE
disable ipv6 entrily ?

### ISSUE THREAD

**Issue by mhf-ir** [go-gost/gost#66]
how can i disable ipv6 entirely  on gost ?

```yaml
services:
  - name: local
    addr: "0.0.0.0:8080"
    handler:
      type: socks5
    listener:
      type: tls
```

```
 sudo netstat -tulpn | grep gost
tcp6       0      0 :::8080                  :::*                    LISTEN      24569/gost          
```
