### ISSUE TITLE
如何用mihomo连接该格式对应的gost服务端 `ss+mws://AEAD_AES_128_GCM:password@domain:8000`

### ISSUE THREAD

**Issue by cesaryuan** [go-gost/gost#675]
如何用mihomo连接该格式对应的gost服务端 `ss+mws://AEAD_AES_128_GCM:password@domain:8000`

我尝试了下面的配置，但是不可以：
```
- name: 'test'
  type: 'ss'
  server: 'domain'
  port: 8000
  cipher: 'aes-128-gcm'
  password: 'password'
  network: 'ws'
  ws-opts:
    path: '/ws'
  smux:
    enable: true
    protocol: 'smux'
```
