### ISSUE TITLE
能否让gost转发前添加ProxyProtocol头部

### ISSUE THREAD

**Issue by SianHH** [go-gost/gost#677]
能否在配置添加rtcp时，能否和haproxy一样，配置send-proxy的metadata，让gost转发前添加ProxyProtocol头部。

目前的gost端口转发时，必须要在gost前面添加haproxy这类会添加proxyProtocol头部的服务，这会额外再占用一个端口，也没办法通过gost的api动态修改一个配置

**Comment by wenerme** [comment]
希望 gost 能支持 send proxy

类似

```bash
gost -L udp://:5353/127.0.0.1:53?send-proxy=1
```

看目前代码里 dialer 都是有处理 proxyPtotocol 选项的，但是实际 dial 的时候并没有关心。


还是说就应该是使用 rtcp 或者 rudp，看打到代码里只有 remote handler 处理 `proxyproto.WrapClientConn`，测试下来这样是可以的

```bash
./gost -L rtcp://:8080/192.168.76.130:80?proxyProtocol=1
```

**Comment by SianHH** [comment]
您好，请问什么时候能支持send-proxy？

**Comment by ginuerzh** [comment]
近期没有时间。

**Comment by ginuerzh** [comment]
The feature already exists: set `proxyProtocol: 1` (v1) or `2` (v2) in the **handler** metadata of your `rtcp`/`rudp`/`tcp`/`udp`/`forward` service, and gost prepends the PROXY protocol header on the outbound connection before forwarding.

```yaml
services:
  - name: service-0
    addr: :8080
    handler:
      type: rtcp
      metadata:
        proxyProtocol: 1
    listener:
      type: rtcp
    forwarder:
      nodes:
        - addr: 192.168.1.10:80
```

Note: the CLI `?proxyProtocol=1` query applies to the **listener** side (receive). For send-proxy it must go under `handler.metadata` as above. In a full reverse tunnel the header's source address is the tunnel peer rather than the original client (relay transports only the destination) — that's a separate protocol change.

See `play/issues/677.yaml` and the `TestProxyProtoSuite` e2e test for a working example.
