### ISSUE TITLE
virtual 连接器不采用 resolver 设置

### ISSUE THREAD

**Issue by iBug** [go-gost/gost#678]
例如：

```yaml
nodes:
  - name: node-0
    resolver: resolver-0
    connector:
      type: virtual
    dialer:
      type: virtual
```

此时如果接收到一个域名请求，该域名并不会发送给 resolver-0 解析，而是通过 `/etc/resolv.conf` 中的服务器解析了。
