### ISSUE TITLE
socks5开启udp无效

### ISSUE THREAD

**Issue by steamsv** [go-gost/gost#69]
根据 https://github.com/go-gost/gost/issues/37 给出的示例，`-O`转换成`yaml`根据实际情况修改，网卡ip为内网IP如下
```
services:
- name: service-2222
  addr: :8080
  interface: 10.82.7.9
  handler:
    type: socks5
    auth:
      username: username
      password: password
    metadata:
      udp: "true"
  listener:
    type: tcp
    metadata:
      udp: "true"
```

`netstat -anp`查看端口监听未发现udp端口8080处于监听状态，tcp监听正常
