### ISSUE TITLE
关于端口范围：多对多转发

### ISSUE THREAD

**Issue by jiangtaixing** [go-gost/gost#694]
根据实例：
`gost -L tcp://:8000-8003/192.168.1.1:8000-8010`
等价于：
```
services:
  - name: service-0
    addr: :8000
    handler:
      type: tcp
    listener:
      type: tcp
    forwarder:
      nodes:
        - name: target-0
          addr: 192.168.1.1:8000
  - name: service-1
    addr: :8001
    handler:
      type: tcp
    listener:
      type: tcp
    forwarder:
      nodes:
        - name: target-1
          addr: 192.168.1.1:8001
  - name: service-2
    addr: :8002
    handler:
      type: tcp
    listener:
      type: tcp
    forwarder:
      nodes:
        - name: target-2
          addr: 192.168.1.1:8002
  - name: service-3
    addr: :8003
    handler:
      type: tcp
    listener:
      type: tcp
    forwarder:
      nodes:
        - name: target-3
          addr: 192.168.1.1:8003
```
如果有300个端口需要转发，是否有更简洁的写法？
