### ISSUE TITLE
udp无法转发

### ISSUE THREAD

**Issue by meteorOSS** [go-gost/gost#700]
``` yaml
services:
- name: service-0
  addr: :1080
  handler:
    type: socks5
    chain: chain-0
    metadata:
      udp: true
      udpBufferSize: 3000
  listener:
    type: tcp
chains:
- name: chain-1
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      addr: ":1080"
      connector:
        type: socks5
        metadata:
          udp: true
      dialer:
        type: udp
- name: chain-0
  hops:
  - name: hop-0
    selector:
      strategy: rand
      maxFails: 1
      failTimeout: 10s
    nodes:
    - name: node-0
      addr: '34.xxx.219.7:9000'
      connector:
        type: socks5
        metadata:
          udp: true
        auth:
          username: 'xxx-11befa6f-400976'
          password: 'wifi-hk---'
      dialer:
        type: tcp
    - name: node-1
      addr: '34.141.xxx.7:9001'
      connector:
        type: socks5
        metadata:
          udp: true
        auth:
          username: '35f9f52a-11befa6f-b2c19b'
          password: 'wifi-hk---'
      dialer:
        type: tcp
    - name: node-2
      addr: '34.xxx.220.7:9001'
      connector:
        type: socks5
        metadata:
          udp: true
        auth:
          username: 'xxxx2a-11befa6f-b2c19b'
          password: 'wifi-hk---'
      dialer:
        type: tcp
```

udp转发没成功，少了什么参数吗

使用sstap连接时

![Image](https://github.com/user-attachments/assets/c66710d2-cb95-45a3-8afc-dc1aef6d8f8a)
