### ISSUE TITLE
Question: how to de-multiplex and forward the traffic (forward inbound TCP and UDP to the different remotes)?

### ISSUE THREAD

**Issue by iybtapgbcu** [go-gost/gost#703]
# Given
gost version: "gost v3.0.0-nightly.20250218 (go1.23.6 linux/amd64)"

gost yaml configuration file:
```yaml
services:
  - name: svc-entrypoint
    addr: [REDACTED]
    handler:
      chain: chain-proxy
      type: socks5
      metadata: {udp: true}  # setting "sniffing: true" seems to have no effect on anything

chains:
  - name: chain-proxy
    selector: {strategy: fifo}
    hops:
      - name: hop-0
        nodes:
          - name: N1
            addr: [REDACTED]
            connector:
              type: SOME-ARBITRARY-CONNECTOR-HERE
              auth:
                username: [REDACTED]
                password: [REDACTED]
            dialer:
              type: SOME-ARBITRARY-DIALER-HERE
-- CUT HERE --
```

# Task
I want to route all the TCP traffic via some arbitrary node named N1 and all the UDP traffic via some arbitrary node named N2.

How do I do that?

I know from the documentation that I can filter by the protocol in the node in the "forwarders" section,
but all nodes in the "forwarders" section seem to be ignored. Probably because the svc-entrypoint is a "socks5" and the N1 is not.

I have also looked into the "reverse proxy tunnel" tutorial, but it does not seem to be related to the task at hand.

Thanks.

**Comment by ginuerzh** [comment]
Implemented in go-gost/x. Use the new `Network()` matcher in your node configuration to route TCP and UDP traffic to different upstreams:

```yaml
services:
  - name: svc
    addr: :1080
    handler:
      type: socks5
      chain: chain-0
      metadata: {udp: true}

chains:
  - name: chain-0
    hops:
      - name: hop-0
        nodes:
          - name: node-tcp
            addr: tcp-upstream:8080
            connector: {type: socks5}
            dialer: {type: tcp}
            matcher:
              rule: "Network(`tcp`)"
          - name: node-udp
            addr: udp-upstream:8080
            connector: {type: socks5}
            dialer: {type: tcp}
            matcher:
              rule: "Network(`udp`)"
```

How it works:
- `router.Dial()` passes `"tcp"` through the chain → hop → matcher → `Network("tcp")` selects the tcp node
- `router.Bind()` (UDP ASSOCIATE) passes `"udp"` / `"udp4"` / `"udp6"` → `Network("udp")` uses prefix matching to select the udp node
- Matchers compose with `&&`, `||`, `!` so you can combine with `Host()`, `Path()`, etc.

**What changed:**
- `core/routing`: added `Network` field to `Request` struct (core v0.4.3)
- `x/routing`: added `network()` matcher function registered as `"Network"`
- `x/hop`: passes `options.Network` to the routing request in `Select()`

Also works for other handlers (HTTP, HTTP2, etc.) that route through chain hops — not just SOCKS5. Any handler that calls `router.Dial()` or `router.Bind()` will get the `Network` value propagated through the matcher.
