### ISSUE TITLE
Provide connector username/password with a file

### ISSUE THREAD

**Issue by Ramblurr** [go-gost/gost#717]
Hi! 

I would like to use a gost config file in a situation where I want the credentials for a connector  loaded from a file, instead of being passed in the configuration file.

https://gost.run/en/reference/configuration/file/#connector <-- connector credentials can only be passed via config file

Would this be possible? Something like:

```yaml
  chains:
  - name: chain-0
    hops:
    - name: hop-0
      nodes:
      - name: node-0
        addr: :8443
        connector:
          type: tunnel
          auth:
              file: /path/to/file/with/username/and/password
          metadata:
            tunnel.id: 9fd6c586-86f9-49c1-a03a-d4876851695a
          dialer:
            type: tcp
```
