### ISSUE TITLE
bypass 可以做成数组吗？

### ISSUE THREAD

**Issue by recall704** [go-gost/gost#73]
```
services:
- name: service-0
  addr: ":8080"
  bypass: bypass-0
  handler:
    type: http
    chain: chain-0
  listener:
    type: tcp
chains:
- name: chain-0
  hops:
  - name: hop-0
    # hop level
    bypass: bypass-1
    nodes:
    - name: node-0
      addr: 192.168.1.1:8080
      # node level
      # bypass: bypass-0
      connector:
        type: http
      dialer:
        type: tcp
bypasses:
- name: bypass-0
  matchers:
  - 10.0.0.0/8
- name: bypass-1
  matchers:
  - 172.10.0.0/16
  - 127.0.0.1
  - localhost
  - '*.example.com'
  - .example.org
```

从外部收集的 ip、域名基本都是分开的多个文件，这样配置的时候就需要写多个。

**Comment by recall704** [comment]
```
services:
- name: service-0
  addr: ":8080"
  bypass: 
      - bypass-0
      - bypass-1
```

**Comment by recall704** [comment]
翻代码发现有这个参数，关闭 issue 了

```
- name: local-redirect
  addr: :12345
  bypasses:
    - bypass-lan
    - bypass-china-ip
    - bypass-china-domain
 ```
