### ISSUE TITLE
请求"DNS代理"增加支持使用本机默认DNS

### ISSUE THREAD

**Issue by aa51513** [go-gost/gost#89]
目前gost的dns代理功能，必须指定forwarder才能够使用，如下所示：
`services:
- name: service-0
  addr: :10053
  handler:
    type: dns
  listener:
    type: dns
    metadata:
      mode: udp
  **forwarder:
    nodes:
    - name: target-0
      addr: 1.1.1.1**`

强制手动指定dns服务器地址，显然不够灵活

我希望能够支持使用当前系统默认DNS，可行的做法有2种：

①不配置forwarder，就自动用系统默认dns；
②将localhost作为addr的时候，就使用系统默认dns；

还请评估一下这个请求

**Comment by ginuerzh** [comment]
forwarder并不是必须的，如果不设置默认使用127.0.0.1:53

**Comment by aa51513** [comment]
> forwarder并不是必须的，如果不设置默认使用127.0.0.1:53

操作系统默认并不会在127.0.0.1:53上监听，能否设计成不配置就使用系统的默认dns？

**Comment by ginuerzh** [comment]
Fixed in [go-gost/x@684a0dd](https://github.com/go-gost/x/commit/684a0dd).

When no `forwarder` and no `dns` metadata are configured, the DNS handler now reads system nameservers from `/etc/resolv.conf` (Unix) before falling back to the hardcoded `127.0.0.1:53`.

This means a minimal DNS proxy config now works out-of-the-box without specifying upstream DNS:

```yaml
services:
- name: service-0
  addr: :10053
  handler:
    type: dns
  listener:
    type: dns
    metadata:
      mode: udp
```

Windows support can be added later via the IP Helper API (`GetAdaptersAddresses`), same approach Go's `net` package uses.
